### ISSUE TITLE
проблемы с плагином diffplugin4modx

### ISSUE THREAD

**Issue by sasha181** [dmi3yy/modx.evo.custom#100]
Использую версию  1.0.13-d6.7
Поставил из репозитория плагин diffplugin4modx

Ошибки сразу две: 
1. в дереве документов при редактировании любого документа выскакиваеи ява-скриптовый алерт "ManagerManager: An error has occurred: TypeError - $j.ddMM is undefined"
2. Подгрузка сохранённых версий не работает. 

Со вторым вопросом несколько разобрался. Там проблема в том, что вызывается напрямую файл assets/plugins/diff/version.ajax.php
В нём используется константа MGR_DIR , но т.к. файл assets/cache/siteManager.php не присоединён, константа не задана и скрпит не работает. 
У себя решил это глобально, чтобы предупредить подобные проблемы в других местах. В .htaccess добавил 
php_value auto_prepend_file "/полный_путь_к_document_root/assets/cache/auto_prepend.inc.php"

с таким содержимым 

    if( !defined(MGR_DIR) && is_file($_SERVER['DOCUMENT_ROOT'] . '/assets/cache/siteManager.php') ) {
        include_once($_SERVER['DOCUMENT_ROOT'] . '/assets/cache/siteManager.php');
    }

а вот с первой проблемой разобраться пока нет времени, да и опыта с modx пока крайне мало. Только начал осваивать.

**Comment by dmi3yy** [comment]
Поправил вот так: 
https://github.com/extras-evolution/diffplugin4modx/commit/97fada3b8685565a8ede05e710f109202ac9b7d6

а первой проблемы в последних версиях сборки уже нет
