### ISSUE TITLE
Refused to set unsafe header "Connection"

### ISSUE THREAD

**Issue by SergeyMiracle** [dmi3yy/modx.evo.custom#137]
В последних двух версиях modx evo периодически пропадает страница правки/создания документа, единственная ошибка Refused to set unsafe header "Connection". Чистил кеш, пробовал с другого компа, картина не меняется. Лечится полной заменой файлов cms, но проблема потом опять появляется... 

https://www.dropbox.com/s/nutd83p6f4ad5xp/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202014-07-22%20%D0%B2%2017.41.16.png

**Comment by keslo** [comment]
Та же проблема. Загрузка админки зависает выдается "Refused to set unsafe header "Connection" при обработке файла mootools.js.

**Comment by dmi3yy** [comment]
Добрался наконецто до решения этой проблемы: 

суть в том что криво настроен  сервер, если в файлике index.php который ведет в админку добавить показ ошибок то увидим следующее: 
http://take.ms/kbmni

Далее гуглим что за ошибка и понимаем что криво настроен путь для хранения сессии а сервере. 

Если нет доступа к php.ini то лечить можно вот так: 
Создаем в корне папку tmp с правами 777 
и правим config.inc.php
http://take.ms/sMDd

**Comment by riamax** [comment]
Решение: Открыть файл manager/includes/config.inc.php и сохранить его в кодировке UTF-8 without bom (UTF-8*)

**Comment by Aligan** [comment]
Не решилась проблема? Описанные здесь методы не помогают
