### ISSUE TITLE
1.0.10-d5.4R -- не сработал встроенный ftp

### ISSUE THREAD

**Issue by jorjik** [dmi3yy/modx.evo.custom#139]
При попытке загрузки или распаковки ZIP файла
пишет ошибка (хостинг tenet.ua) http://SSMaker.ru/04dea43d/

**Comment by dmi3yy** [comment]
Скорей всего из за того что сервер на Винде 
на реальном сервере проблем не наблюдаю да и на MAC OS локально тоже все ок
