### ISSUE TITLE
Ошибка при изменении пароля по ссылке в шапке

### ISSUE THREAD

**Issue by Pathologic** [dmi3yy/modx.evo.custom#162]
Если ввести пароль, например, короче 6 символов, то получим A possible CSRF attempt was detected. No referer was provided by the server.

**Comment by AgelxNash** [comment]
Не актуально

**Comment by Pathologic** [comment]
Проверил: сначала сообщение на белом фоне, что пароль не подходит, потом A possible CSRF attempt was detected. No referer was provided by the server, ну и во фрейме открывается админка:

![-1](https://cloud.githubusercontent.com/assets/3012304/6428240/9002b3a4-bfab-11e4-809e-ac3ff549d4f8.png)

**Comment by AgelxNash** [comment]
[Судя по коду процессора](https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/processors/save_password.processor.php) и [CSRF защиты]( https://github.com/dmi3yy/modx.evo.custom/blob/f29725950db38dfdc567a09a8806f937ccb8475b/manager/index.php#L225-L239), могу предположить следующее:
- MODX_SITE_URL отличен от HTTP_REFER. Возможно редактировали assets/cache/siteHostnames.php, возможно используется кириллический домен. Может быть сервер что-то шаманит с HTTP_REFER.
- После отправки формы методом POST, браузер не корректно реагирует код ```history.back(-1);```. Попробуй сохранить новый плагин с названием, которое уже используется. Если проблема повториться, а различий между MODX_SITE_URL и HTTP_REFER нет, то скорее всего дело именно в history.back()

**Comment by Pathologic** [comment]
Все проще оказалось. У кнопки "Сохранить" href="#", поэтому history.back(-1) добавляет хэш к адресу и из-за этого возникает ошибка. Заменил href="#" на href="javascript:void(0)", теперь ошибки нет.
