### ISSUE TITLE
Cache by Agel_nash 

### ISSUE THREAD

**Issue by dmi3yy** [dmi3yy/modx.evo.custom#169]
#1 Настройки кеширования документа

https://github.com/modxcms/evolution/blob/bugfix/manager/includes/document.parser.class.inc.php#L497
Вот это дело вынести в методб т.е. зачастую бывает ситуация, когда плагином/сниппетом влияют на GET массив и уже https://github.com/modxcms/evolution/blob/bugfix/manager/includes/document.parser.class.inc.php#L743 получается совсем не то
- добавить событие для плагина что б влиять на эти параметры можнобыло даст возможность для разных страниц настраивать разный набор параметров. 
#2 добавить возможность влиять на AliasListing 

2) Вот тут https://github.com/modxcms/evolution/blob/bugfix/manager/includes/document.parser.class.inc.php#L268  подключается файл с DocumentListing, и всегда по коду он берется из массива. А что если до создания кэша/после получения кэша вызывать событие, чтобы иметь возможность модифицировать этот массив (хотя бы пока так). Это бы позволило без гемороя решать задачи с кастомизацией кеширования сайтов любых объемов. Допустим исключить из кеша служебные страницы, страницы товаров (если они являются папками) и т.д.
#3 уменьшить чуток кеш за счет  переносов строк

3) убрать из файла https://github.com/modxcms/evolution/blob/bugfix/manager/processors/cache_sync.class.processor.php переносы строк (нахрена они в кэше). Зачастую из-за этого получается сэкономить пару КБ. Что в конечном счете всяко положительно сказывается на производительности сайта
#4) разнести по файлам кеш елементов

4) Я бы еще хотел видеть разнесеные по файлам кэши плагинов/сниппетов/чанков/документов и т.д.) ($this->pluginElvent/chunkCache/snippetCache/DocumentListing) и т.д.
#5 Сохранять в кеш

Для сниппетов и чанков добавить галочку: сохоранять в кэш (в базе даже есть поле cache_type)
[07.10.14, 10:18:57] Agel_Nash: а ты чанки в кэш пихать и не будешь если галочка сохранять в кэш снята.
[07.10.14, 10:19:44] Agel_Nash: Только метод getChunk нужно подправить как это в runSnippet https://github.com/modxcms/evolution/blob/bugfix/manager/includes/document.parser.class.inc.php#L2395
[07.10.14, 10:19:59] Agel_Nash: чтобы он подгружался из базы если нет чанка в кэше
[07.10.14, 10:20:32] Agel_Nash: сам подумай, зачем тебе чанк письма с сообщением об успешном заказе на странице регистрации?
[07.10.14, 10:21:02] Agel_Nash: а +1 запрос на странице оформления заказа это не так уж и долго (учитывая, что поиск идет по PrimaryKey индексу + чанков как правило не бывает больше 100)
[07.10.14, 10:21:58] Agel_Nash: Зато все чанки это распухание глобального кеша который реально и так из-за DocumentListing распухает

**Comment by AgelxNash** [comment]
На мой взгляд, вот что осталось для полного завершения:
 - Разнести по файлам кеш элементов (*$this->pluginElvent/chunkCache/snippetCache/DocumentListing*)
 - Для сниппетов и чанков добавить галочку: сохранять в кэш (*в базе даже есть поле cache_type*)
 - Добавить событие до загрузки основного кеш-файла siteCache.idx.php
 - В метод DocumentParser::checkCache добавить событие OnCheckWebPageCache, чтобы через плагин на этом событии можно было подменить способ чтения данных из кеша. Ну и как следствие, доработать событие OnBeforeSaveWebPageCache, чтобы не только чтение, но и запись можно было переопределить
 - Перенести событие OnSiteRefresh из файла manager/actions/refresh_site.dynamic.php в метод DocumentParser::clearCache(). И разбить вызов на 2 части - без параметров (полная очистка); с параметром в виде списка ID, как в DocLister (частичная очистка)
 - Вынести в настройки MODX галочку, которой определять необходимость создания $modx->documentMap
 - Добавить возможность подменять путь assets/cache/

В целом делов тут не так уж и много. Зато уже хоть как-то можно будет влиять на кеш.

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/29
