### ISSUE TITLE
refactor phpError by Agel_Nash

### ISSUE THREAD

**Issue by dmi3yy** [dmi3yy/modx.evo.custom#170]
Метод phpError посмотри. Он строит таблицы. При чем верстка жестко заложоена в методе. У тебя есть класс MakeTable! https://github.com/modxcms/evolution/blob/bugfix/manager/includes/extenders/maketable.class.php почему бы его не задействовать для большей семантичности (тем более верстка таблиц в админке на этом классе и строится)

**Comment by AgelxNash** [comment]
Замыкания могут использовать $this только с PHP 5.4, нужен патч в стиле
```php
$modx = $this;
function() use($modx){ $modx->htmlspecialchars(); };
```
