### ISSUE TITLE
Управление action  в админку   by Agel_Nash

### ISSUE THREAD

**Issue by dmi3yy** [dmi3yy/modx.evo.custom#172]
Событие OnManagerPageInit должно иметь возможность подмены $action
2) Все switch($action) вынести в файлы. Т.е. проверять для начала file_exists(..../customAction/$action.php), а затем file_exists(..../action/$action.php) и подключать его если он есть
3) Код вида
include_once "header.inc.php";
include_once "actions/..........php";
include_once "footer.inc.php";
Изменить до вида ->render($action); Где после выяснения что за экшин работает вызвается нечто-следующее
if($this->showHeader){
 include_once "header.inc.php";
}
include($action)
if($this->footer){
 include_once "footer.inc.php";
}
Просто сейчас открыв CMS и index.php файл сразу складывается впечатление, что тебе передают привет из 90хы
а так будет уже что-то больше похожее на 20 век с элементами ООП и возможность модифицировать любую страницу админку

**Comment by AgelxNash** [comment]
Тут напрашивается отдельный класс для шаблонизации. Как например [\Module\Template](https://github.com/AgelxNash/DocLister/blob/master/assets/lib/Module/Template.php) из DocLister'a. После внедрения такого класса для шаблонизации, логичным продолжением списка задач по укрощению админки, может стать задача #204.

**Comment by dmi3yy** [comment]
Сейчас это все работает путем того что все файлы беруться из темы админки если там есть 
тоесть создаем новую тему и там правим ядро как нудно. Но думаю и это скоро пересмотрим
