### ISSUE TITLE
Перенос класса PHPThumb

### ISSUE THREAD

**Issue by Pathologic** [dmi3yy/modx.evo.custom#173]
Когда-то поднимался уже этот вопрос. Но теперь обновился метод loadExtension и от переноса будет больше пользы.
Первый вопрос - в какую папку переносить, extenders или controls? 
Второй - оставить ли заглушку в папке snippets/phpthumb на тот случай, если какие-то дополнения подключают класс оттуда?

**Comment by Pathologic** [comment]
https://github.com/dmi3yy/modx.evo.custom/pull/208

**Comment by AgelxNash** [comment]
На мой взгляд, рановато закрыли тикет. Рефакторинг метода loadExtender #188 позволяет регистрировать кастомные экстендеры. А класс PHPThumb используется много где - значит требуется еще плагин обязательно ставить.

Событие onBeforeLoadExtension нужно, но к класс PHPThumb должен быть в комплекте с MODX. Разместить исходники класса следует в папке manager/includes/controls, а правило для загрузки экстендера в файле includes/extenders/phpthumb.extenders.inc.php.

**P.S.** Предыдущий рефакторинг метода loadExtender #20 приводил к ошибке, когда происходило обращение к не существующей переменной класса DocumentParser. В остальном, тот способ был рабочий, просто никто не захотел отлавливать переменные которые забыли объявить в классе. Но спустя время, я вижу огромный недостаток того способа - он не позволял загружать классы из разных мест, т.к. все классы должны были располагаться в папке includes/extenders/custom/. Сейчас же (*с событием onBeforeLoadExtension*) мы можем грузить что угодно и от куда угодно. А значит, есть возможность подключить composer через плагин к событиям "OnWebPageInit, OnManagerPageInit, OnPageNotFound" и регистрировать экстендеры без дополнительного include.

**Comment by dmi3yy** [comment]
Будем переделывать с vendor в новой ветке уже
