### ISSUE TITLE
cleanDocumentIdentifier обрезает  алиас. 

### ISSUE THREAD

**Issue by radist** [dmi3yy/modx.evo.custom#175]
При определенном сочетании параметров. В частности русские буквы, но и не только. Например с немециким ä так же могут возникнуть проблемы.

собственно проблемная строка:

$q= basename($q);

В итоге имеем на некоторые урлы с такими символами 404 ошибку.

Лечится установкой setlocale(LC_ALL, 'ru_RU.UTF-8'); для русского где нибудь в index.php

Понятно, что решение не кошерное и в массы так нельзя. В инсталере например setlocale делается в языковом файле, для каждого языка свое. При работе парсера вроде ни чего подходящего нет куда всунуть. Так, что проблема пока без решения.

PS: про то что не латиница не по феншую я в курсе, мне уже так досталось.

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/18
