### ISSUE TITLE
Добавить в Eform

### ISSUE THREAD

**Issue by Typodin** [dmi3yy/modx.evo.custom#197]
Eform добавляет value для всех инпутов, хотя по спецификации инпутам типа file и image иметь его не положено. В итоге ведет к ошибке валидации. Решение:

В файле после строки 966 добавить следующий код:

```
case 'file':
	return "<input$t/>";
case 'image':
	return "<input$t/>";
```
Подробно: modx.im/blog/questions/2958.html

**Comment by dmi3yy** [comment]
готово
