### ISSUE TITLE
Баг в if

### ISSUE THREAD

**Issue by Typodin** [dmi3yy/modx.evo.custom#202]
Есть вызов разных чанков, в зависимости от уровня:

[[if? &is=`[*parent*]:=:0` &then=`{{menu_category}}` &else=`{{menu_category_in}}`]]

или просто:

[[if? &is=`[*parent*]:=:0` &then=`{{menu_category}}`]]

Если есть соответствие условие, срабатывает нормльно. Но если нет, то произвольно добавляет в код число. Выглядит это примерно так: http://joxi.ru/5md0Y64upZZgm1

**Comment by dmi3yy** [comment]
Как минимум @TPL:имя чанка

Отправленно с телефона
www.dmi3yy.com

**Comment by Typodin** [comment]
А я то наивный, думал что @CHUNK - оказывается это уже не модно. Да, с @TPL нет баги.
