### ISSUE TITLE
Точка возврата в процессорах

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#204]
Собственно сабж. Хочется иметь возможность подменить точку возврата после совершения каких-либо действий. Ну допустим, после [удаления документа](https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/processors/delete_content.processor.php#L124)

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/19
