### ISSUE TITLE
Использование экстендера getUserData

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#219]
Этот экстендер получает IP пользователя и версию браузера. Этим нужно пользоваться в ядре. Но предварительно нужно дописать определение IP, чтобы оно было более точным. Позаимствовать алгоритм можно из файла [accesscontrol.inc.php](https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/accesscontrol.inc.php#L166-L174), а лучше из  [DocLister'a](https://github.com/AgelxNash/DocLister/blob/master/assets/lib/APIHelpers.class.php#L153-L222)  - там используется примерно такой же (только более продвинутый).

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/30
