### ISSUE TITLE
Метод для получения времени

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#221]
Давно напрашивается метод для получения времени с учетом смещения в системной настроке.

``` php
function getTime(){
return time() + $this->config['server_offset_time'];
}
```

В коде часто встречаются моменты, где используется то просто time(), то time() + смещение.  Это нужно исправлять.

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/32
