### ISSUE TITLE
Стилизация страницы webAlertAndQuit

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#222]
После вызова события webAlertAndQuit загружается белая страница с текстом. Смотрится позорно и давно напрашивается подключение стилей из файла [manager/includes/header.inc.php](https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/header.inc.php)

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/26
