### ISSUE TITLE
Работа с переменными snippetsTime, snippetsCount и snippetsCode

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#223]
В методе [DocumentObject::outputContent()](https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/document.parser.class.inc.php#L661-L665) есть работа с этими переменными. Но вот данные в эти переменные ни от куда не поступают.

А еще, переменная [snipCode](https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/document.parser.class.inc.php#L1085) по всей видимости должна называться snippetsCode.

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/33
