### ISSUE TITLE
Стек вызовов сниппетов/плагинов

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#225]
PR #212 решающий задачу #170 добавляет удобный вывод стека методов которые привели к ошибке. В этот вывод удобно было бы еще добавить стек вызовов сниппетов/плагинов.

Можно даже не изобретать велосипед, а подсмотреть как это реализовано в [ClipperCMS](https://github.com/ClipperCMS/ClipperCMS/blob/develop/manager/includes/document.parser.class.inc.php#L1235-L1257) методами registerEvalInfo() и unregisterEvalInfo(). Или более продвинутая версия из [BolmerCMS](https://github.com/BolmerCMS/BolmerCMS/blob/master/core/app/Bolmer/Parser.php#L37-L90) засекающая время выполнения элементов.

Вот пример массива который на выходе создает Bolmer
![Вот пример массива который на выходе создает Bolmer](https://monosnap.com/file/lkctlWAnx0EY3XR5BcWfhkxziFjvkX.png)
Как видно, сразу видны и передаваемые параметры, и время выполнения, и кто инициатор вызова и т.д. и т.п. Остается только оформить вывод человеческим образом и будет сказка.

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/34
