### ISSUE TITLE
Best Practices Japanese

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#227]
- ~~Установка заголовков Last-Modified и Not Modified~~
- ~~Рефакторинг DocumentParser::getLoginUserID()~~
- ~~Именной кеш для служебных страниц~~
- [Разнести по файлам кеш элементов](https://github.com/modxcms-jp/evolution-jp/blob/stable/manager/includes/cache_sync.class.php#L271-L276) - то, о чем я говорил в задаче #169 
- [Загрузка данных из кеша в случае необходимости](https://github.com/modxcms-jp/evolution-jp/blob/stable/manager/includes/document.parser.class.inc.php#L67-L77) - я предлагал добавил галочку для отключения кеширования documentMap. А они пошли еще дальше и этот подход лично мне, нравится больше
- [Оставить в config.inc.php только конфиги](https://github.com/modxcms-jp/evolution-jp/blob/stable/install/tpl/config.inc.tpl), а всю логику и установку не определенных констант вынести в [специальный файл](https://github.com/modxcms-jp/evolution-jp/blob/stable/manager/includes/initialize.inc.php). Правда некоторые скрипты могут пытаться самостоятельно имитировать деятельность index.php и уже сразу после подключения config.inc.php начинают работать с константами.

**Comment by AgelxNash** [comment]
После вот этого коммита https://github.com/dmi3yy/modx.evo.custom/commit/988866ff3dd6c7c71eb9c0436f22ea4b316569a1#diff-b91fad0266a33c1d4d87dff876939692R1049 появился вызов не существующего метода DocumentParser::setSnippetCache() в DocumentParser::evalSnippets().

Этот метод напрямую связан с задачами:
* Разнести по файлам кеш элементов
* Загрузка данных из кеша в случае необходимости

**Comment by AgelxNash** [comment]
Именной кеш для служебных страниц, конфликтен с плагином кастомной маршрутизации на базе события OnPageNotFound. Если раньше при кешировании с учетом GET параметров, можно было кешировать виртуальные страницы, то теперь кеш для них будет общим. Выход один - добавить событие OnMakePageCacheKey в плагин и самостоятельно задавать ключ кеша отличный от notfound

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/36
