### ISSUE TITLE
Типа баг: Ditto.tpl + чанк

### ISSUE THREAD

**Issue by jorjik** [dmi3yy/modx.evo.custom#235]
Словом так: если из чанка дитто вынести фрагмент в др. чанк -- то он не работает корректно; 
Пример: у меня был такой фрагмент
    [[if?is=`[+inventory+]:=:1` &then=`
        <span class="available">
					        <img src="/bitrix/templates/electro/images/iconAvailable.png" alt="В наличии">
					        В наличии
		</span>` 
&else=`<span class="noAvailable">
						    <img src="bitrix/templates/electro/images/iconnoavailable.png" alt="Под заказ">
						    Под заказ					      
		</span>	`]]    
в карточке каталога; и при инклюде он дал инверсию!

**Comment by dmi3yy** [comment]
проверьте еще раз должно работать просто IF работает внутри Дитто без проблем.
