### ISSUE TITLE
Расширить страницу системной информации

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#236]
* Если на сервере отключен phpinfo(), то не выводить ссылку на страницу phpinfo
* Добавить версию PHP в краткую характеристику сервера

**Comment by radist** [comment]
https://github.com/dmi3yy/modx.evo.custom/commit/0224769bd9cadc02c1b363dac9a5ad9c1c5cf438

**Comment by radist** [comment]
По первому, достаточно function_exists ? Гугль находит совсем уже экзотические варианты, с проверкой тремя способами: анализом значения параметра disable_functions в файле php.ini, а также через функции PHP function_exists и is_callable.

**Comment by dmi3yy** [comment]
Да надо чем проще тем лучше

**Comment by dmi3yy** [comment]
Дума первый пункт не критичен
