### ISSUE TITLE
Tree - bug

### ISSUE THREAD

**Issue by jorjik** [dmi3yy/modx.evo.custom#237]
Дерево документов не хранит состояние;

версия: 1.0.15-d6.18
консоль: Uncaught TypeError: Object [object Object] has no method 'live'

**Comment by jorjik** [comment]
походу дело в 
   assets/plugins/managermanager/js/jquery-1.9.1.min.js

**Comment by dmi3yy** [comment]
В последних версиях не замечал такого бага
