### ISSUE TITLE
Галерея

### ISSUE THREAD

**Issue by kumirska** [dmi3yy/modx.evo.custom#243]
Добрый день. Как вы разрешаете вопрос с галереями? Полазив в сборнике дополнений, я понял, что галереи либо очень старые, 2010-2013 года, либо уже не поддерживаются актуальными версиями modx. Я не часто делаю что-то на modx в последнее время, но появилась необходимость поставить галерею на 1.0.15

**Comment by dmi3yy** [comment]
Рекомендую или : 
EvoGallery http://extras.evolution-cms.com/packages/gallery/evogallery.html
Или : 
SimpleGallery  http://modx.im/blog/addons/2652.html

1 Вариант проще 
2 Вариант гибче и функциональней

**Comment by kumirska** [comment]
Огромнейшее спасибо, Дмитрий!

**Comment by kumirska** [comment]
Я установил менеджер пакетов, установил evoGallery все как по маслу, создались сниппет, модуль и плагин, появился модуль в списке модулей. Есть возможность нажать кнопку SELECT, все загружается, но после загрузки фотки не отображаются на этой странице, нет возможности добавить тайтлы как раньше или сортировать драг-н-дропом, так как фотки вообще не выводятся после загрузки и на предыдущей стр.в списке ресурсов написано images:0 хотя физически они все-таки на сервере лежат. MODx 1.0.15, evoGallery качал тут https://github.com/extras-evolution/EvoGallery. Кто-нибудь сталкивался??

**Comment by dmi3yy** [comment]
Проверить права доступа к файлам 
Могут создаватся не с теми правами потому и не отображаются

Отправленно с телефона
www.dmi3yy.com

**Comment by kumirska** [comment]
@dmi3yy я тестирую локально из-под виндоус 7 на OpenServer. Не решаюсь на боевом сразу пилить.

**Comment by dmi3yy** [comment]
То что глючит на винде локально это вполне нормально

Отправленно с телефона
www.dmi3yy.com

**Comment by 4ernika** [comment]
Всем привет. Подскажите, а как в EvoGallery вывести одно любое нужное мне фото из целой галереи? К сожалению гугл не рулит :( Где найти этот злощастный id фото?

**Comment by kumirska** [comment]
@4ernika глянь в html коде там либо id либо дата аттрибут был вроде

**Comment by 4ernika** [comment]
@kumirska Не, нифига... в HTML альбом представляется так:
`<h1>Название альбома</h1>
<div class="divgalleryimage"><a href="/assets/galleries/21/IMG_2767.JPG" class="fancybox" rel="gallery1" title=""><img src="/assets/galleries/21/thumbs/IMG_2767.JPG"></a></div>
<div class="divgalleryimage"><a href="/assets/galleries/21/IMG_2775.JPG" class="fancybox" rel="gallery1" title=""><img src="/assets/galleries/21/thumbs/IMG_2775.JPG"></a></div>
<div class="divgalleryimage"><a href="/assets/galleries/21/IMG_2777.JPG" class="fancybox" rel="gallery1" title=""><img src="/assets/galleries/21/thumbs/IMG_2777.JPG"></a></div>
<div class="divgalleryimage"><a href="/assets/galleries/21/IMG_2796.JPG" class="fancybox" rel="gallery1" title=""><img src="/assets/galleries/21/thumbs/IMG_2796.JPG"></a></div>`

По этому вопрос пока открыт:
- как в EvoGallery вывести одно любое нужное мне фото из целой галереи?

**Comment by dmi3yy** [comment]
Такие вопросы лучше писать на modx.im 
А ответ на ваш вопрос есть в документации в примере вывода фото 

Отправлено с iPhone

**Comment by kumirska** [comment]
@4ernika не на странице с галереей в публичной вьюхе, а в админке, где ты можешь сортировать/добавлять/удалять изображения.

**Comment by 4ernika** [comment]
@kumirska а, ну да, заметил что-то подобное. там когда мышкой находишь на фото на значок карандаша - в строке состояния браузера появляется длинная ссылка и там есть некий id. Попробовал вот так:
[[EvoGallery? &docId=`21` &display=`single` &picId=`1144` &itemTpl=`item_list_galery1`]]

Отлично. работает. всем спасибо :)

@dmi3yy Очень долго мучился с этой проблемой. Гугл оказался бесполезен :( Не уже ли до меня ни кто не пытался вывести одно любое фото (по id) из целой галереи? К сожалению [документация](https://rtfm.modx.com/extras/evo/evogallery) очень скудная и там нет примеров как вывести одно фото. Там только пример с &display=`images`, а мне нужен &display=`single`.

**Comment by kumirska** [comment]
@4ernika Я пытался! Но сразу нашел в админке в исходном коде страницы :8ball:
