### ISSUE TITLE
Weblogin не регистрирует пользователей

### ISSUE THREAD

**Issue by Typodin** [dmi3yy/modx.evo.custom#249]
При попытке регистрации получем пустое белое окно и сообщение: SMTP connect() failed. 
При этом из eform сообщения отправляются нормально с использованием SMTP
В файле weblogin.common.inc.php прописано подключение SMTP

**Comment by AgelxNash** [comment]
в функции [sendMail](https://github.com/extras-evolution/Weblogin/blob/master/assets/snippets/weblogin/weblogin.common.inc.php#L49-L80) происходит работа с PHPMailer на прямую. Хотя правильней работать через экстендер MODxMailer или даже метод DocumentParser::sendmail()

Поэтому проблема скорее в сниппете weblogin, нежели в ядре.
