### ISSUE TITLE
PhpThumb

### ISSUE THREAD

**Issue by kumirska** [dmi3yy/modx.evo.custom#250]
Добрый вечер, друзья. Пытаюсь реализовать на сайте генерацию превью для галереи, взял за основу phpthumb из официальной сборки modx evolution. Но беда, не сохраняется изображение
Вот мой пробный вызов:
```code
[[phpthumb? &input=`[*small-gallery*]` &options=`w=150,h=76,far=C,bg=FFFFFF` ]]
```
Выводит на экран
```code
assets/cache/images/content/about/150x76-6.51e.jpg
```
При этом никакой ошибки не возникает, но и физически файл не создается в папке cache. Тестирую на OpenServer PHP 5.5 на win 7. MODx evolution 1.0.15
 
Подскажите, в чем может быть причина? phx (не знаю, нужен или нет) но стоит и используется. 

Не сочтите за наглость, искал, читал, пробовал phpthumbof, и через phx его пробовал затестить, но эффекта 0. Я вообще потерял нить с modx, вещи, которые были просты и документированны, вызывают теперь недоразумения :( 

Даже думал обойти mm_ddresizeimage раз на то пошло, прописав в mm_rules 
```code
mm_ddResizeImage('small-gallery', '', '', 260, 195);
```
но настройки Конфигурации MODx перекрывают эти значения..а если поставить в конфигурации макс ширину и высоту миниатюр в значени 0, то они вообще тогда загружаются в папку .thumbs в истинном размере.

**Comment by dmi3yy** [comment]
Скорей всего причина в настройках опенсервера 
В целом надо смотреть лог там должно что то быть

Отправленно с телефона
www.dmi3yy.com

**Comment by kumirska** [comment]
@dmi3yy спасибо, буду пробовать на боевом ;)

**Comment by dmi3yy** [comment]
Тьфу ты все ж верно :) а обернуть путь в тег img пробовали :)
