### ISSUE TITLE
 Обнаружил один небольшой баг в Вашей новой сборке - MODX EVO 1.1b-d7.1 При создании плагина и установке события "OnLoadDocumentObject" выдается белый экран.

### ISSUE THREAD

**Issue by dmi3yy** [dmi3yy/modx.evo.custom#257]
Дмитрий, добрый день! Обнаружил один небольшой баг в Вашей новой сборке - MODX EVO 1.1b-d7.1 При создании плагина и установке события "OnLoadDocumentObject" выдается белый экран. Как я понимаю после него ничего не происходит дальше, ибо если в самом плагине сделать вывод чего либо, то все норм. А вот в версии 1.1b-d7.0.16 все нормально

**Comment by dmi3yy** [comment]
проверил в 7.1.4 все работает

**Comment by pbweb** [comment]
Не работает на 7.1.5
document.parser.class.inc.php:1505
место:
			if(is_array($out)){
				$documentObject = $out;
			}
Должно быть:
			if(is_array($out) && is_array($out[0])){
				$documentObject = $out[0];
			}

**Comment by dmi3yy** [comment]
Надо проверить на 7.1.6 

Отправлено с iPhone
