### ISSUE TITLE
ChoiceTV не переносится в секцию

### ISSUE THREAD

**Issue by Typodin** [dmi3yy/modx.evo.custom#258]
Параметр с типом chiceTV не переносится в нужную секцию:
<code>
mm_ddMoveFieldsToSection('params', 'sec','','5');
</code>
это единственный параметр, который не переносится.

**Comment by dmi3yy** [comment]
это проблема с choiceTV 
перенес тикет сюда: 
https://github.com/extras-evolution/choiceTV/issues/2
