### ISSUE TITLE
При попытке сделать копию ресурса: Cannot modify header information

### ISSUE THREAD

**Issue by yeysman** [dmi3yy/modx.evo.custom#259]
Вот такая ошибка появляется.
Warning: Cannot modify header information - headers already sent by (output started at \manager\includes\document.parser.class.inc.php:1054) in \manager\processors\duplicate_content.processor.php on line 35

При этом дубликат (визуально) не появляется, но если обновить страницу - дубликат отображается.
В строке ocument.parser.class.inc.php:1054 закомментировал echo $msg; Проблема решилась. Но я только начинаю работать с modX и не думаю что это правильное решение )

**Comment by wmlev** [comment]
Подобного рода проблему наблюдал при установленном модуле EvoGallery. Вот этот файл /assets/plugins/managermanager/widgets/evogallery/evogallery.php должен быть именно с кодировкой utf-8. Когда поправлял этот момент, проблема исчезала.

**Comment by russelgal** [comment]
потверждаю

**Comment by dmi3yy** [comment]
готово
