### ISSUE TITLE
resourse.php

### ISSUE THREAD

**Issue by nartzis** [dmi3yy/modx.evo.custom#264]
Строки 462-463
$rc = $this->modx->db->select('value', $this->_table['site_tmplvar_contentvalues'], "contentid = '{$fields['contentid']}' AND tmplvarid = '{$fields['tmplvarid']}'");
if ($row = $this->modx->db->getRow($rs)) {

Во второй строчке вместо $rs должно быть $rc 
Ну или в первой $rs

**Comment by dmi3yy** [comment]
спасибо исправил
