### ISSUE TITLE
Error in tvs - missing assets/tvs folder

### ISSUE THREAD

**Issue by Nicola1971** [dmi3yy/modx.evo.custom#266]
Just installed 1.1b-d7.1.2 on my local wamp (windows) and i have an error in all Tvs editing pages.
The system can not find assets/tvs folder 

I'm not a coder, but seems caused by these new (from evo 1.0.15) lines in mutate_tmplvars.dynamic.php:

https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/actions/mutate_tmplvars.dynamic.php#L354

Just add the required ***tvs*** folder in assets to fix the issue

**Comment by dmi3yy** [comment]
ok thanks. fix it
