### ISSUE TITLE
eForm вырезает аттрибут required из чанка

### ISSUE THREAD

**Issue by DanyaDaro** [dmi3yy/modx.evo.custom#267]
При попытке сделать валидацию форм на стороне клиента (установка аттрибута required на input), eform начинает сопротивляться и обертывает required в класс.
На выходе получается: < input ... class=" required" >

**Comment by kchurilo** [comment]
Используйте required="required"

**Comment by dmi3yy** [comment]
через class eform добавляет собственную проверку потому и конфликт просто называйте по другому класс
