### ISSUE TITLE
Пункты в настройках "Использовать SEO Strict URLs" и "Добавлять слэш к контейнеру"

### ISSUE THREAD

**Issue by EGO7000** [dmi3yy/modx.evo.custom#268]
Весь вечер убил, чтобы понять откуда ноги растут! Всегда ставил плагином, а тут увидел пункты - подумал, что в ядро запили. Но при этом получал либо зацикливание, либо не работал параметр seoOveride. Потом поставил плагин, появились двойные слэши на контейнерах и полных хаос с работой сайта и формированием sitemap.xml :)
В общем, решил только отключением этих 2 пунктов и по старинке плагином. Хорошо бы было либо полностью вшить функционал плагина, либо в Readme (а лучше в тексте этих настроек) написать, мол так и так, в ядре только такой функционал.
И ещё во время экспериментов, ловил глюк, если суффикс для страниц убрать совсем.
За сборку спасибо! :+1:  Только осваиваю git, надеюсь в дальнейшем помогу со сборкой :)

**Comment by dmi3yy** [comment]
Проверьте плз еще раз. 
Если стоит плагин Seo Strict Url  и включен одноменный параметр в ядре то будет ругаться можно использовать или то или то но никак не вместе

**Comment by EGO7000** [comment]
Проверил - при включении функции в ядре (и соответственно отключении плагина) параметр seoOverride никак не влияет на отображение страницы в адресной строке и файле sitemap.xml.
Сейчас понимаю, что собственно, надеется на это и не стоило, т.к. при поиске по исходникам этот параметр нигде не отображён, а пункта для него нет (как в настройках у плагина), т.е. в ядре зашит только базовый функционал.

Кстати, с прошедшими! :)

**Comment by dmi3yy** [comment]
seoOverride - так это ж параметр для sitemap ?  

ну или напиши что оно должно делать и я предложу оптимальный вариант решения вопроса )


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 11 января 2016 г. в 15:34, EGO7000 написал:

> seoOverride

**Comment by EGO7000** [comment]
seoOverride используется не только для sitemap, но и для отображения адреса страницы в командной строке.
Например, у меня есть 3 типа ресурсов: 
1) стандартные страницы (используют суффикс);
2) каталоги (они же папки, они же контейнеры) - используют слэш на конце
3) "ресурсы-агрегаторы" (к ним же я причисляю системные документы, н-р, обработчик ajax-запросов) - они без слэшей в конце.

Так вот для подобных логических разграничений можно использовать seoOverride со стандартным плагином SEO Strict URL, просто выбирая в настройках страницы как она будет отображаться - по умолчанию или же как мне необходимо.

А через настройки ядра нельзя реализовать следующее (или я не смог найти):
www.sitename.ru/samepage.html
www.sitename.ru/catalog/
www.sitename.ru/ajax

**Comment by dmi3yy** [comment]
Ну да в ядре такого нет.  
хотя  
1 так и есть по умолчанию  
2 тоже работает
3 я весь аякс делаю через плагин на 404 и по факту так и получается без / и .html  
+ если это писать в ядро то логично не через ТВ а добавлять доп опцию в стандартные поля

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 11 января 2016 г. в 16:48, EGO7000 написал:

**Comment by EGO7000** [comment]
Про трюк с 404 читал, но я же не только ajax таким образом делаю, также разграничиваю статические ресурсы и динамически формирующиеся. Тут много вариантов, те же страницы /403 и /404, /login и /logout, прочие обработчики.

Да, логично доп.опцию. Но там ещё небольшой баг может получиться при генерация url. Т.е. нужно проверить функцию MakeUrl().

**Comment by dmi3yy** [comment]
Надо продумать логику реализации и можно добавить доп параметр. 
Просто я использую чуть по другому и для той же странички 404 не вижу проблемы .html )
просто плагин seo strinct сильно нагружает сайт если идет доп обработка ссылок

**Comment by EGO7000** [comment]
По идее всё равно в доп.поле нужно указывать название TV-параметра, чтобы у каждой странички можно было выбрать как её выводить. Либо вообще запилить это в Тип ресурса: веб-страница, веб-ссылка и просто alias. Кстати, заодно можно веб-ссылку поправить, чтобы в MakeUrl() он обрабатывал правильно, и не генерировал сначала внутреннюю ссылку, а потом редирект на внешнюю.

**Comment by dmi3yy** [comment]
а ссылка и так генерится верно в дитто если писать не [~[+id+]~] а [+url+]
