### ISSUE TITLE
systemCacheKey и пользовательская маршрутизация. Баг

### ISSUE THREAD

**Issue by webber12** [dmi3yy/modx.evo.custom#269]
Обновил систему и столкнулся с багом плагина "SEO pagination for Ditto" на событии onPageNotFound (преобразует страницы по адресу news/page2 в страницы дитто news?start=20 через $modx->sendForward) - когда в кэш попадала страница 404, то и все остальные страницы новостей переставали работать. Начал копать и понял, что проблема кроется в методе makePageCacheKey() https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/document.parser.class.inc.php#L518 который при наличии systemCacheKey его и возвращает - https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/document.parser.class.inc.php#L522-L524. Но перед событием onPageNotFound данный ключ systemCacheKey всегда устанавливается в https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/document.parser.class.inc.php#L249 $this->systemCacheKey = 'notfound'; Т.е. ломается вся пользовательская маршрутизация, когда раньше на одной странице 404 можно было повесить множество разных кэшей за счет параметров $_GET, то теперь там кэш один и чаще всего - со страницы 404 получается.

Возможно я где-то чего-то не так понял или не заметил (было бы замечательно), но, похоже проблема именно в этом.

**Comment by webber12** [comment]
Простейшее решение - сброс (очистка) указанной переменной перед внутренним редиректом sendForward. Т.е. итого это выглядит так в плагине для события onPageNotFound

<code>
//ставим уникальный $_GET параметр для нужной страницы, чтобы кэш был уникальным
$_GET['ourpage'] = $uniq_param_for_page;

//сбрасываем переменную systemCacheKey, чтобы она не была одна и та же для всех страниц 'notfound' и не мешала искать нужный кэш
$modx->systemCacheKey = '';
//собственно берем нужную страницу по ее docid и подсовываем вместо несуществующей
$modx->sendForward($docid);
</code>

**Comment by AgelxNash** [comment]
Это не баг, а обратно не совместимые изменения. Раньше для 404 страницы генерировалось куча кеш файлов. Сейчас один. Но чтобы решать проблемы поднятые в этом вопросе, systemCacheKey определяется до события onPageNotFound. Т.е. для того, чтобы как-раз таки дать возможность программисту определять в какой кеш файл скидывать информацию.

**Comment by AgelxNash** [comment]
В общем об этом я говорил тут #227 
> Именной кеш для служебных страниц, конфликтен с плагином кастомной
> маршрутизации на базе события OnPageNotFound. Если раньше при
> кешировании с учетом GET параметров, можно было кешировать виртуальные
> страницы, то теперь кеш для них будет общим. Выход один - добавить
> событие OnMakePageCacheKey в плагин и самостоятельно задавать ключ
> кеша отличный от notfound
