### ISSUE TITLE
Меню - баг или фича?

### ISSUE THREAD

**Issue by jorjik** [dmi3yy/modx.evo.custom#270]
перенёс вёрстку с доп. тегами http://SSMaker.ru/f5459530/
получил http://SSMaker.ru/bf03e4eb/

Modx 1.0.15-d6.18

**Comment by dmi3yy** [comment]
Там у Вайфиндера есть новый параметр ) 
поставь &entityEncode=`false`

**Comment by jorjik** [comment]
спасибо, бро
