### ISSUE TITLE
Увиличить максимальную длину имени CustomTV

### ISSUE THREAD

**Issue by AgelxNash** [dmi3yy/modx.evo.custom#276]
Поле type в таблице site_tmplvars имеет длину в 20 символов. Из них 10 уходит на префикс ```custom_tv:```, Таким образом, максимальная длина имени кастомного ТВ не может превышать 10 символов. Хочется больше:-)

**Comment by dmi3yy** [comment]
сделал ) но только для новых установок что б в апдейты не пулить
