### ISSUE TITLE
Ошибка Deprecated: preg_replace()

### ISSUE THREAD

**Issue by Serg28** [dmi3yy/modx.evo.custom#281]
В версии PHP 5.5 , МОДх 1.0.15-d6.18 предупреждает:
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /home/u577518795/public_html/demo/manager/includes/document.parser.class.inc.php on line 1295

Похоже, что пришла пора вводить функцию preg_replace_callback вместо preg_replace

**Comment by dmi3yy** [comment]
поставте версию 1.1b-7.1.3 )  и будет все ок  

--  
Lukianenko Dmytro
Web developer  
http://dmi3yy.com


понедельник, 16 ноября 2015 г. в 19:08, Sergey написал:

**Comment by Serg28** [comment]
Поставил. К сожалению, ругается на строку 1373:
$documentSource= preg_replace($in, $out, $documentSource);

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /home/.../public_html/demo/manager/includes/document.parser.class.inc.php on line 1373

**Comment by dmi3yy** [comment]
ок проверю  

--  
Lukianenko Dmytro
Web developer  
http://dmi3yy.com


понедельник, 16 ноября 2015 г. в 21:27, Sergey написал:

**Comment by radist** [comment]
есть такое

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /public_html/manager/includes/document.parser.class.inc.php on line 1373

**Comment by dmi3yy** [comment]
Есть такое  если поправить то нормально заводиться с php 7 (кроме install)

Вот пулреквест на эту тему но еще не тестил 

https://github.com/dmi3yy/modx.evo.custom/pull/285

**Comment by dmi3yy** [comment]
Готово
