### ISSUE TITLE
Баг с событиями onWebPageInit и OnPageNotFound на несуществующей странице

### ISSUE THREAD

**Issue by webber12** [dmi3yy/modx.evo.custom#283]
Какой-то глюк с событиями onWebPageInit и OnPageNotFound случился между версиями 7.0.15 и 7.1.1. на несуществующей странице. Для проверки делаю простенький плагин на эти оба события:

```
switch ($modx->Event->name) {
    case 'OnPageNotFound':
        echo 'page';
        break;
    case 'OnWebPageInit':
        echo ' ok ';
        break;
    default:
        break;
}
```

Раньше если страницы нет, то срабатывало только OnPageNotFound (было написано page), а сейчас срабатывает сначала onWebPageInit (пишет ok), а уже потом OnPageNotFound (пишет следом page). Т.е. отрабатываются оба события (хотя onWebPageInit не должно быть вообще — потому что на этой несуществующей странице нет даже $modx->documentIdentifier, который часто используется на событии onWebPageInit).

**Comment by Pathologic** [comment]
В 7.1.3 нет бага.

**Comment by webber12** [comment]
Ну если только в последний момент что-то поменялось - т.к. в 7.1.2 он все еще был, а 7.1.3 я еще нигде не ставил :)

**Comment by dmi3yy** [comment]
Проверил на 7.1.4 все ок
