### ISSUE TITLE
Что это?!

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#284]
https://github.com/dmi3yy/modx.evo.custom/blob/master/assets/modules/store/js/store.js

**Comment by dmi3yy** [comment]
Скрипт работы с репозиторием:) если хорошо посмотришь он уже не менялся более 2-х лет 
потому вирусов там нет. просто закодирован что б работал модуль только с нужным репозиторием :)

**Comment by atomoc** [comment]
))

**Comment by atomoc** [comment]
Похоже store не работает, будет?

**Comment by dmi3yy** [comment]
Если удалишь то не будет :) 
Анивирусы нормальные пишут что возможно там вирус но не более )

ai-bolit так поступает. 

Ну а антивирус на ukraine.com.ua не придерается ни как
