### ISSUE TITLE
preg_replace

### ISSUE THREAD

**Issue by myindexlike** [dmi3yy/modx.evo.custom#302]
Error : preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead
Error information	
ErrorType[num]	DEPRECATED[8192]
File	/home/sites/globalpartszone_/public_html/dostup/includes/document.parser.class.inc.php
Line	1373
Source	$documentSource= preg_replace($in, $out, $documentSource);

**Comment by dmi3yy** [comment]
Обновитесь до 7.1.4 и будет все ок. там это исправленно

**Comment by myindexlike** [comment]
Спасибо -- С уважением, Ковальчук Руслан    04.01.2016, 15:18, "Dmytro Lukianenko" <notifications@github.com>:Обновитесь до 7.1.4 и будет все ок. там это исправленно—Reply to this email directly or view it on GitHub.
