### ISSUE TITLE
Плагин Watermerker не конвертит в расширение заданное в f=[png|jpg|gif]

### ISSUE THREAD

**Issue by wlatt1991** [dmi3yy/modx.evo.custom#306]
Плагин накладывает на картинку watermark, но оставляет исходное расширение файла при загрузке, т.е. плагин игнорирует параметр f, сам я допилил плагин для конверта в нужное расширение, но без правки файла manager/media/browser/mcpuk/core/browser.php не обошлось, т.к. в нём нарезается миниатюра загруженной картинки с исходным расширением. А в плагине я удаляю картинку с исходным расширением и создаю с новым расширением. Надо из плагина вернуть новый адрес картинки в manager/media/browser/mcpuk/core/browser.php для правильной нарезки миниатюры. Надеюсь правильно расписал. Хотелось бы в будущем видеть этот плагин в extras и чтобы конвертирование работало (с нарезкой превьюх), т.к. часто исходная картинка в png, а на выходе требуется jpg

**Comment by dmi3yy** [comment]
Обычно для этого использую phpthumb через него можно и ватермарки накладывать и все остальное) 
если есть надобность в плагие скиньте что и где надо допправить что б коректно работало + линк на плагин добавлю в extras
