### ISSUE TITLE
Tiny MCE Emmet - конфликт с HTML5 тегами header и footer

### ISSUE THREAD

**Issue by Aharito** [dmi3yy/modx.evo.custom#308]
У меня MODX EVO Custom 1.1b-d7.1.3, а значит Tiny MCE 3 (В Tiny MCE используется Emmet, насколько я понимаю. )

При нажатии Tab он преобразовывает header и footer в {{header}} и {{footer}} соответственно. Это не позволяет использовать HTML5 теги header и footer внутри тега article:
```
main>article>(header>h1.page-header)+section+footer
```
Такой шаблон не работает как надо.

Считаю, что чанк типа {{header}} легче написать **вручную**, а вот корректное преобразование шаблонов Emmet важно.

**Comment by dmi3yy** [comment]
Поддерживаю с HTML5 теперь не коректон поправлю

**Comment by dmi3yy** [comment]
fixed
