### ISSUE TITLE
YAMS проблема

### ISSUE THREAD

**Issue by xaos86** [dmi3yy/modx.evo.custom#317]
YAMS не работает в последниеи версии, а имено не показавает никаких шаблонов, а когда нажимаеш update, он тупа создаеот TV. Помогите.

**Comment by wmlev** [comment]
Тоже такая проблема

**Comment by xaos86** [comment]
Посмотри в папке manager/includes/config.inc.php и измени из mysqli в mysql.

**Comment by wmlev** [comment]
да. заработало! Только вот пока не разобрался почему в документах поля относящиеся к разным языкам не хотят во вкладках быть

**Comment by xaos86** [comment]
:) В документе  assets / modules / yams / yams.mm_rules.inc.php надо в конце поминяти: 
mm_moveFieldsToTab(
        $tvString
        , $langId
        , $rolesAccessList
        , $activeTemplateList
        );

на:
mm_ddCreateSection(
			$langId
			, $langId
			, $langId
			, $rolesAccessList
			, $activeTemplateList
		);
		mm_ddMoveFieldsToSection(
			$tvString
			, $langId
			, $rolesAccessList
			,$activeTemplateList
		);
      if ( $rolesNoAccessList != '!' )
      {
        mm_hideFields(
          $tvString
          , $rolesNoAccessList
          , $activeTemplateList
          );
      }

Примерно так мне кажется, но посмотри уже сам.
