### ISSUE TITLE
Отваливается managermanager на php 7.0.2

### ISSUE THREAD

**Issue by Archifl** [dmi3yy/modx.evo.custom#320]
не работает плагин managermanager 0.6.2 при переключении сервера на php 7.0.2 
Версия MODX	 	1.1RC-d7.1.5

Скриншоты:
![2016-02-15 16 15 42](https://cloud.githubusercontent.com/assets/17251585/13049748/1fd26f06-d400-11e5-9b25-5f36da8c6359.png)
![2016-02-15 16 15 46](https://cloud.githubusercontent.com/assets/17251585/13049749/2001862e-d400-11e5-8e0f-d50c770f6caa.png)
![2016-02-15 16 18 17](https://cloud.githubusercontent.com/assets/17251585/13049751/200a4084-d400-11e5-9c1d-8975bc847d0e.png)
![2016-02-15 16 18 31](https://cloud.githubusercontent.com/assets/17251585/13049750/2001f1ea-d400-11e5-8d60-296b89cf66be.png)

**Comment by dmi3yy** [comment]
Если проблема еще актуальна на свежих версиях просьба написать + скрин с консоли браузера
