### ISSUE TITLE
mm_ddSelectDocuments

### ISSUE THREAD

**Issue by mediakot** [dmi3yy/modx.evo.custom#326]
Добавлю сюда, так как в оригинальном mm_ddSelectDocuments этой проблемы нет. Думаю, что это в это сборке правилось.
Итак: этот виджет не работает, так как в отличии от оригинала добавлен ещё один параметр, позволяющий дублировать значения (allowDoubling). Чтобы работало нужно в 29 строке файла ddselectdocuments.php закавычить значение параметра  allowDoubling:
function mm_ddSelectDocuments($tvs = '', $roles = '', $templates = '', $parentIds, $depth = 1, $filter = '', $max = 0, $labelMask = '[+title+] ([+id+])',**$allowDoubling = 'false'**)

**Comment by dmi3yy** [comment]
готово
