### ISSUE TITLE
Риски между body

### ISSUE THREAD

**Issue by Petalsoft** [dmi3yy/modx.evo.custom#330]
Фото: http://pastenow.ru/Upload/Paste/KYG3.jpg http://pastenow.ru/Upload/Paste/KYG0.jpg
После установки заметил.

**Comment by dmi3yy** [comment]
выключите включите tinyMCE4 в плагинах    


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 17 марта 2016 г. в 11:05, Мотчаний Сергій написал:

**Comment by ProjectSoft-STUDIONIONS** [comment]
В файле assets/plugins/tinymce4/plugin.tinymce.php удалить два слеша в начале файла.
Пул отправил.

**Comment by dmi3yy** [comment]
Пасиб ) 
Уже принял
