### ISSUE TITLE
Почему не работает сайт с Shopkeeper?

### ISSUE THREAD

**Issue by ghost** [dmi3yy/modx.evo.custom#331]
Error : mysql_query(): Access denied for user ''@'localhost' (using password: NO) в чем может быть ошибка?

**Comment by dmi3yy** [comment]
обновите шопкипер через  exstras и все будет работать   
а то вы MODX обновили а SHK нет  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 17 марта 2016 г. в 16:38, Мотчаний Сергій написал:
