### ISSUE TITLE
Перестал работать сниппет sitemap из репозитория

### ISSUE THREAD

**Issue by doggydogg-spb** [dmi3yy/modx.evo.custom#334]
После обновления перестал работать сниппет sitemap из репозитория. На чистой установке та же история.
Все настройки по дефолту. PHP 5.3.
Ошибка.
MODX Parse Error
Error : htmlentities() expects parameter 2 to be long, string given
ErrorType[num]	WARNING[2]
File	/home/c/site/public_html/assets/snippets/sitemap/snippet.sitemap.php
Line	184
Source	$url = htmlentities($url, ENT_XML1); //format all special chars to html entities
Current Snippet	sitemap

Встречал топик, но там другая ошибка - http://modx.im/blog/questions/2978.html

**Comment by dmi3yy** [comment]
встречал уже просто закоментируй эту строку чуть позжее разберусь откуда такой баг взялся
