### ISSUE TITLE
"Название ресурса в дереве" - не работает

### ISSUE THREAD

**Issue by doggydogg-spb** [dmi3yy/modx.evo.custom#335]
В сборке 1.1-d8 перестала работать настройка "Название ресурса в дереве".

**Comment by dmi3yy** [comment]
не вижу проблемы: 
http://take.ms/dBbZz

если поле которое вы там выводите не заполненно то выводит все равно pagetitle

**Comment by doggydogg-spb** [comment]
Старнно, может движок криво встал, но как-то так... В настройках "Название ресурса в дереве": [*menutitle*], но какой параметр не ставлю, и заполняю соответствующее поле, всёравно реакции нет...
https://yadi.sk/i/R6Wu1-IDqZH7N

**Comment by dmi3yy** [comment]
может быть проверял как раз на свежеустановленной сборке которую поставил утром все ок было

**Comment by googan** [comment]
столкнулся с такой же проблемой на 2х последних сайтах на 1.1-d8 http://prntscr.com/awyaan
