### ISSUE TITLE
Событие clearCache

### ISSUE THREAD

**Issue by radist** [dmi3yy/modx.evo.custom#336]
Событие clearCache вызывает при очистке кеша сайта в ручную и ни где больше, где есть такая конструкция.

`$modx->clearCache('full');`

Может быть стоит вызов события делать в методе?

https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/includes/document.parser.class.inc.php#L2561

**Comment by ProjectSoft-STUDIONIONS** [comment]
https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/processors/save_content.processor.php#L427
https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/processors/save_content.processor.php#L660

При сохранении документа, если в свойствах документа выбрано свойство "Очистить кэш", кеш сайта полностью очищается.

**Comment by radist** [comment]
Я неудачно выразился.

`$modx->invokeEvent("OnSiteRefresh");`

Речь о вызове события в методе clearCache. Сейчас оно вызывается только при ручной очистке кеша https://github.com/dmi3yy/modx.evo.custom/blob/47dbe8cea84cf6f5ccf115cb96232f07554f084a/manager/actions/refresh_site.dynamic.php#L26

**Comment by dmi3yy** [comment]
Ну так это событие и сделанно на ручную очистку кеша :) 
так всегда и было

**Comment by ProjectSoft-STUDIONIONS** [comment]
Тогда объясняйте, зачем, для чего, в какие моменты это требуется.
На данный момент, то на что вы ссылаетесь реализовано для работы менеджера/админа в админ части.
Что-то мне подсказывает, что вы ни в ту сторону копаете в реализации задуманного.
Определите настройками, какая страница должна кешироваться или не кешироваться. Если вообще кеш не нужен, то установите в настройках сайта по умолчанию не кешированные страницы, чтобы не настраивать каждую страницу вручную.
Либо вам нужно написать свой плагин/сниппет для реализации более конкретной задачи.

**Comment by radist** [comment]
> Ну так это событие и сделанно на ручную очистку кеша :) 
> так всегда и было

так, на что тогда повесится, что бы выполнять код плагина при изменениях на сайте? Конкретно, генерация sitemap. Стандартные варианты sitemap не подходят.

**Comment by dmi3yy** [comment]
Я бы написал плагин на сохранение документа
+ с проверкой новый документ ли и поменялся ли алиас что б не перегенеривать лишний раз сайтмап

**Comment by noizo** [comment]
> Конкретно, генерация sitemap. Стандартные варианты sitemap не подходят.

Вы счажите чем Вам seo4evo не понравилось. По моему очень хорошо создает sitemap, и позволяет правильно настраивать все необходимое

**Comment by radist** [comment]
1. Тот sitemap не может сгенерировать карту, не хватает лимитов на хостинге.
2. Не умеет делать sitemap index и несколько отдельных sitemap

**Comment by ProjectSoft-STUDIONIONS** [comment]
> Не умеет делать sitemap index и несколько отдельных sitemap

Для этого достаточно написать свой сниппет, в параметры которого вы передадите ID ресурсов дополнительных карт сайта.
sitemap умеет делать карту для родителя документов. Внимательно почитайте комментарий в файле сниппета sitemap. Соответсвенно это и есть решение для создания нескольких карт, что и приведёт к меньшей нагрузке на сервер при генерации sitemap.

**Comment by radist** [comment]
ProjectSoft, я modx c 2009 года знаю. Мало того, я дедушку его знаю. Показать как он выглядел в 2003 - 2004 годах?

Если мне не походит, значит не подходит. Мне не надо по родителям. Я использую класс для генерации, который сам бьет по нужному количеству, сбрасывает из памяти в файл по заданным лимитам. И прочее, и прочее. 

Еще я не хочу, снипет, я хочу

```
$index = new Index($sitemap);
$index->write();
```

Я сам сторонник, оставаться в пределах готовых решений и в рамках философии движка. Но сейчас не тот случай. Да и вопрос был о другом. 

Собственно вопрос в том почему не срабатывает событие очистки кеша, при его очистке. По текущей логике работы оно должно называться 

`OnManualSiteRefresh`

**Comment by ProjectSoft-STUDIONIONS** [comment]
@radist да и мне как бы лет не мало )))
При ручной очистке в папке кеша что-то остаётся?

**Comment by dmi3yy** [comment]
на ручную очистку можно повесть доп события :) поэтому оно и надо 

а по части очистить кеш можно вызывать только для одного документа или для всех 
как раз  'full' появилось не так давно до этого нужно было чистить по другому
