### ISSUE TITLE
Подружить store с https

### ISSUE THREAD

**Issue by noizo** [dmi3yy/modx.evo.custom#337]
При работе сайта на https не работает модуль Extras.

**Comment by achekalin** [comment]
При попытке зайти модуль Extra на сайте, работающем по https, происходит попытка подгрузки списка ресурсов для установки через js с http-адреса, что дает ожидаемый результат:

> Mixed Content: The page at 'https://domain.ru/manager/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://extras.evolution-cms.com/get.php?get=start'. This request has been blocked; the content must be served over HTTPS.
> XMLHttpRequest cannot load http://extras.evolution-cms.com/get.php?get=start. Failed to start loading.

Что обидно, при попытке открыть список объектов по https по адресу http://extras.evolution-cms.com/get.php?get=start , получаем редирект на этот же адрес, но по http. 

Поправить ситуацию, вероятно, возможно либо включением поддержки отдачи контента по https на extras.evolution-cms.com, либо деланием прокси для такого рода запросов в php-коде модуля (т.е. на extras.evolution-cms.com фактически будет ходить php, а js запрашивать список объектов уже у php).

**Comment by dmi3yy** [comment]
Подружил

**Comment by achekalin** [comment]
Вот новость так новость! СПАСИБО!

**Comment by achekalin** [comment]
Однако есть проблема: у меня, например, сайт отдается через схему, где фонтэнд делает https, а бекэнд только выдает странички по http (фронтэнд - это Cloudfront, но то же можно и на nginx + apache+mod_php представить). И в этой ситуации модель store нормально не работает, т.к. в его шаблоне происходит подключение site_url, а она задается как http://имя-домена.tld, а не https://имя-домена.tld.

Вылечилось указанием путей к файлам без использования имени домена, т.е. вместо **site_url**/assets/... сделал просто /assets/... Может быть, в шаблонах в модуле store эту идею учесть?

**Comment by dmi3yy** [comment]
Так там вроди только для апдейта модуля есть указание пути 

Отправлено с iPhone
