### ISSUE TITLE
Заменить везде вызов скриптов с http:// на //

### ISSUE THREAD

**Issue by noizo** [dmi3yy/modx.evo.custom#338]
По принципу

http://ajax.googleapis.com/ajax/libs/…
на //ajax.googleapis.com/ajax/libs/...

В результате при включенном https на сайте, все библиотеки будут продолжать работать.

**Comment by ProjectSoft-STUDIONIONS** [comment]
@noizo в каких решениях вы встречали подобные проблемы?
Если это сторонние расширения, то вопросы нужно сыпать туда.
К примеру, данная проблема есть у виджета ddymap разработчиком которого является @DivanDesign.

**Comment by noizo** [comment]
Если не ошибаюсь, во всех встроенных в сборку админских шаблонах, шрифты и скрипты пришлось править, или только шрифты. Сейчас не вспомню уже. Но оно есть.

**Comment by ProjectSoft-STUDIONIONS** [comment]
Да, точно есть. Проверил на сайте с https. Точно есть в шаблоне D3X. Просто сам я всегда использую MODxRE.

**Comment by dmi3yy** [comment]
Проверил все работает на D3X на https 
только проблема со store но это отдельная история сейчас поставлю сертификат провериМ)
