### ISSUE TITLE
Возвращаемые значения плагинов

### ISSUE THREAD

**Issue by bagi091** [dmi3yy/modx.evo.custom#342]
Появилась необходимость дополнять documentObject данными из произвольной таблицы, и как видно в коде, если плагин на событие OnAfterLoadDocumentObject вернул массив, первый элемент которого массив, то переменная documentObject будет перезаписана, но ничего не получается из-за того что по-умолчанию плагины могут возвращать только строку (в файле document.parser.class.inc.php строка 4334). 
Если записать $this->_output = $msg; то все будет работать.

**Comment by Pathologic** [comment]
В плагине, чтобы вернуть не строку, нужно вместо вызова метода $modx->event->output() записывать значение сразу в $modx->event->_output.

**Comment by bagi091** [comment]
Спасибо, я так и сделал, но забыл, что открывал вопрос)
