### ISSUE TITLE
evobabel-0.2 - Не работает на версии MODX EVO 1.1-d8.0 от 11.04.2016 (((

### ISSUE THREAD

**Issue by wmlev** [dmi3yy/modx.evo.custom#350]
Не выводит на странице ресурса блок для создания страниц для других языков и перехода на такую же страницу, только на другом языке. Все делаю по инструкции. Всегда получалось. На данной версии не могу запустить (((.

**Comment by bagi091** [comment]
Тоже столкнулся с этой проблемой, но удалось ее решить, в ближайшее время отпишу

**Comment by bagi091** [comment]
Упс. поторопился я, оказалось что с плагином evobabel та же ерунда, так что сейчас готовлю pull в котором предложу переписать часть, где формируется кэш сниппетов и плагинов.

**Comment by Pathologic** [comment]
@bagi091 Попробуйте вот это https://github.com/dmi3yy/modx.evo.custom/pull/353

**Comment by bagi091** [comment]
@Pathologic К сожалению, Ваше решение не помогает в этой ситуации. Попробую описать ситуацию подробнее. Задача состоит в том, чтобы правильно объединить две "конфигурации по умолчанию" (модуля и плагина/сниппета). Это происходит в файле cache_sync строки 224 и 238. Там стоит проверка на пустоту строки, но в новых версиях modx пустая "конфигурация по-умолчанию" сохраняется в базу как  {}. Модуль сохраняет свои настройки таким же образом, либо пустой, либо полный json, который в любом случае отличается от пустой строки. В итоге когда мы попадаем на те самые строки 224 и 238, то именно из-за этого мы получаем конструкцию вида {} {} (два json через пробел), которую нельзя распарсить ни как json, ни как старый стиль хранения параметров. 

Если расчитывать на то, что "параметры по умолчанию" модуля и плагина/сниппета всегда либо в старом формате, либо в новом, то правильно объединить их не так уж и сложно, но если окажется что модуль хранит параметры в json а сниппет/плагин в старом формате, то тут решение задачи становится похожим на костыль (хотя при этом подозреваю что таких ситуаций не должно быть много)

Задачу можно упростить если сделать в классе document parser метод декодирования старого формата в json. Сейчас это делается на стороне клиента через js.

**Comment by Pathologic** [comment]
Понятно, тут параметры считаются строками. Может будет лучше при сохранении парсить через $modx->parseProperties(), а потом сохранять итоговый массив настроек в виде json?

**Comment by bagi091** [comment]
Я думал об этом, но меня остановили два момента
Первый: Будет запускаться событие OnParseProperties, хотя это можно обойти через тот же переключатель что и в $modx->sendErrorPage()
Второй: Нужно ли в siteCache.idx хранить подписи и другую служебную информацию параметров по умолчанию? Потому что в этом варианте параметры будут храниться в формате key=>value

**Comment by Pathologic** [comment]
Нет, будет только ассоциативный массив (параметр => значение) с теми настройками, которые заполнены - моя правка как раз это и исправляет.

**Comment by Pathologic** [comment]
А в parseProperties можно добавить параметр fire_events = null и по нему проверять, нужен ли вызов события.

**Comment by bagi091** [comment]
Касательно последнего комментария. Посмотрел внимательнее и понял что это лишнее, так как достаточно не передавать $elementName и $elementType

**Comment by bagi091** [comment]
А на счет Вашей правки немного не согласен, что если пустое значение параметра является значением, которое в плагине/сниппете/модуле проходит проверку на соответствие типу? Например if ($param5 === '') В случае если мы не включим param5 в массив всех параметров как раз из-за того что он пустой, мы можем нарушить работу чужих разработок

**Comment by Pathologic** [comment]
Такое поведение было до нововведений, даже в большинстве сниппетов:
```
if (!isset($paramname)) $paramvalue = 'default';
```

**Comment by bagi091** [comment]
Да, во многих сниппетах так и есть, но мало ли, всякое бывает. 
Я думаю что все равно любой значение введенное пользователем даже пустое, должно передаваться в параметры

**Comment by Pathologic** [comment]
Тогда поломается еще и DocLister, потому что там используется такой метод:
```
public static function getkey($data, $key, $default = null)
    {
        $out = $default;
        if (is_array($data) && (is_int($key) || is_string($key)) && $key !== '' && array_key_exists($key, $data)) {
            $out = $data[$key];
        }
        return $out;
    }
```
Если сохранять пустые значения, то этот метод никогда не вернет $default.

**Comment by bagi091** [comment]
Убедили))

**Comment by bagi091** [comment]
А можно тогда задать вопрос для чего нужна проверка if (is_array($row))  ? Как я понимаю в новых настройках это условие всегда должно быть истинным

**Comment by Pathologic** [comment]
До правки у меня эти настройки криво парсились из старых, так что наверное не нужна проверка.

**Comment by bagi091** [comment]
Понял, спасибо)

**Comment by Pathologic** [comment]
Потом проверю, если проблема не будет возникать при установке плагинов, то и проверку уберу.

**Comment by bagi091** [comment]
Нет, как раз-таки проверка нужна, я уже проверил. мы ведь сохраняем значения в виде json строки key => value. Получается что после создания файла siteCache.idx $row не массив а строка.

**Comment by Pathologic** [comment]
Тогда пусть будет :smile:

**Comment by Typodin** [comment]
Правка #353 для eFilter не сработала, все равно ошибка. Почитал переписку, но новых идей не возникло, может есть еще варианты?

**Comment by bagi091** [comment]
Тут должна быть не только правка #353, но и небольшое изменение кода, а именно файл cache_sync строки 223-225 и 237-239 необходимо заменить на следующие. 
`if ( ($tmp1['properties'] != '' && $tmp1['properties'] != '{}') || ($tmp1['sharedproperties'] != '' && $tmp1['sharedproperties'] != '{}') ) {
					$tmpProp = array_merge($modx->parseProperties($tmp1['sharedproperties']),$modx->parseProperties($tmp1['properties']));
					if(!empty($tmpProp))
						$tmpProp = $this->escapeSingleQuotes(json_encode($tmpProp));
					$tmpPHP .= '$s[\'' . $this->escapeSingleQuotes($tmp1['name']) . 'Props\']' . "='" . $tmpProp . "';";
				}`
`if ( ($tmp1['properties'] != '' && $tmp1['properties'] != '{}') || ($tmp1['sharedproperties'] != '' && $tmp1['sharedproperties'] != '{}') ) {
					$tmpProp = array_merge($modx->parseProperties($tmp1['sharedproperties']),$modx->parseProperties($tmp1['properties']));
					if(!empty($tmpProp))
						$tmpProp = $this->escapeSingleQuotes(json_encode($tmpProp));
					$tmpPHP .= '$p[\'' . $this->escapeSingleQuotes($tmp1['name']) . 'Props\']' . "='" . $tmpProp . "';";
				}`

**Comment by Typodin** [comment]
Капец, заработало! Спасибо, куда слать на пиво с чипсами?)

**Comment by bagi091** [comment]
@Typodin а что Вы исправляли?

**Comment by Typodin** [comment]
И 353 от Максима и то что в почту пришло: 

`if ( ($tmp1['properties'] != '' && $tmp1['properties'] != '{}') || ($tmp1['sharedproperties'] != '' && $tmp1['sharedproperties'] != '{}') ) {
$tmpProp = array_merge($modx->parseProperties($tmp1['sharedproperties']),$modx->parseProperties($tmp1['properties']));
if(!empty($tmpProp))
$tmpProp = $this->escapeSingleQuotes(json_encode($tmpProp));
$tmpPHP .= '$s[\'' . $this->escapeSingleQuotes($tmp1['name']) . 'Props\']' . "='" . $tmpProp . "';";
}
if ( ($tmp1['properties'] != '' && $tmp1['properties'] != '{}') || ($tmp1['sharedproperties'] != '' && $tmp1['sharedproperties'] != '{}') ) {
$tmpProp = array_merge($modx->parseProperties($tmp1['sharedproperties']),$modx->parseProperties($tmp1['properties']));
if(!empty($tmpProp))
$tmpProp = $this->escapeSingleQuotes(json_encode($tmpProp));
$tmpPHP .= '$p[\'' . $this->escapeSingleQuotes($tmp1['name']) . 'Props\']' . "='" . $tmpProp . "';";
}`

**Comment by Pathologic** [comment]
```
if ( ($tmp1['properties'] != '' && $tmp1['properties'] != '{}') || ($tmp1['sharedproperties'] != '' && $tmp1['sharedproperties'] != '{}') )
```
Эта проверка может быть не нужна, потому что в tmpProp по-любому окажется массив

**Comment by bagi091** [comment]
эта проверка нужна на тот случай если и модуль и сниппет/плагин не имеет параметров по умолчанию ни в старом виде, ни в новом

**Comment by bagi091** [comment]
Если убрать эту проверку, то для каждого сниппета и плагина будет дважды вызваться
$modx-> parseProperties() на этапе добавления их в кэш, причем часто это будет вхолостую

**Comment by Pathologic** [comment]
```
var_dump($modx->parseProperties(''));
//array (size=0)
```

**Comment by Pathologic** [comment]
Но вообще да, смысл парсить, если парсить нечего изначально

**Comment by bagi091** [comment]
Ну да, лишней эта проверка не будет. Можете включить это исправление в свой pull?

**Comment by SebastianoFereiro** [comment]
Внимательно прочитал все выше перечисленное, но так и не смог запустить evobabel на версии MODX EVO 1.1-d8.0 от 11.04.2016
Подскажите, есть ли решение, возможно где-то вариант вернуть старую логику или внести изменения сразу в значения в бд

**Comment by dmi3yy** [comment]
Скачайте версию 8.1.2 с гитхаба на верси 8.0 есть проблемы с параметрами плагина потому и глючит  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 22 сентября 2016 г. в 15:54, SebastianoFereiro написал:

**Comment by Typodin** [comment]
Не забудьте отписаться заработало или нет)

**Comment by SebastianoFereiro** [comment]
update до 1.1-d8.1.2 вылечил проблему полностью, а вот попытка точечно поиграться с 
document.parser.class.inc.php и cache_sync.class.processor.php не дали результата.
dmi3yy огромное спасибо за решение и вообще за Ваши сборки.

**Comment by SebastianoFereiro** [comment]
Но проблема не одна,  еще не работает плагин evoBabelPlaceholder и плейсхолдер [+switchLang+] на новой 8.1.2 версии. Ошибок в консоли нет.

**Comment by dmi3yy** [comment]
Это должно работать а там когда ставили настроили коректно общие параметры между модулем и сниппетом плагином ?

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 23 сентября 2016 г. в 13:32, SebastianoFereiro написал:

**Comment by SebastianoFereiro** [comment]
Модуль EvobabelLexicon 
+общие параметры
-> конфигурация :
id шаблона языка - 14 (шаблон язык)
id TV языковых связей - 15 (tv related)
-> Зависимости
evoBabel	- Plugin
evoBabel - Snippet
lang - Snippet

Плагин
evoBabel
Импортировать общие параметры модуля:   EvobabelLexicon  - Сохранить
Проверка системных событий - OnPageNotFound, OnDocFormSave, OnBeforeEmptyTrash, OnEmptyTrash, OnWebPageInit,OnDocDuplicate.

Сниппет
evoBabel

Импортировать общие параметры модуля: EvobabelLexicon  - Сохранить

Есть вариант как глянуть, более подробно связку?

**Comment by SebastianoFereiro** [comment]
Как я понимаю, пока решения нет?

**Comment by dmi3yy** [comment]
Проблема с расшаренными параметрами все вопросы сюда: 
https://github.com/dmi3yy/modx.evo.custom/issues/356

в планах сегодня пофиксить
