### ISSUE TITLE
Перенос ресурса в папку собственного потомка

### ISSUE THREAD

**Issue by nartzis** [dmi3yy/modx.evo.custom#352]
Сейчас меняя родителя ресурса, можно указать одного из своих потомков. 
После такой процедуры сайт падает, так как не может построить дерево алиасов (зацикливается).
Хорошо бы сделать проверку, не является ли новый родитель самим документом или одним из его потомков, что бы избежать таких ситуаций.

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/23
