### ISSUE TITLE
evobabel-0.2 - Не работает плагин evoBabelPlaceholder и [+switchLang+]

### ISSUE THREAD

**Issue by zloyxrom** [dmi3yy/modx.evo.custom#354]
Не работает плагин evoBabelPlaceholder плейсхолдеры [%ключ%] и плейсхолдер [+switchLang+] на новой версии MODX EVO 1.1-d8.0 от 11.04.2016.

**Comment by Pathologic** [comment]
https://github.com/dmi3yy/modx.evo.custom/pull/349
https://github.com/dmi3yy/modx.evo.custom/pull/353

**Comment by zloyxrom** [comment]
Заработало. Но теперь опять не работает это - Не выводит на странице ресурса блок для создания страниц для других языков и перехода на такую же страницу, только на другом языке.

**Comment by zloyxrom** [comment]
Заработало. Но теперь опять не работает это - Не выводит на странице ресурса блок для создания страниц для других языков и перехода на такую же страницу, только на другом языке.

**Comment by zloyxrom** [comment]
Сделал откат для проверки -> показывает блок создания страниц для других языков и перехода на, ну и конечно не Не работает плагин evoBabelPlaceholder плейсхолдеры [%ключ%] и плейсхолдер [+switchLang+]

**Comment by Pathologic** [comment]
Может быть поломали что-то еще, нужно смотреть код фрейма, есть ли там блок с переходами на страницы. Если есть, то видимо с js что-то не так.

**Comment by dmi3yy** [comment]
Это связанно с ошибкой : https://github.com/dmi3yy/modx.evo.custom/issues/356
