### ISSUE TITLE
Удалить из дерева кнопку "Элементы"

### ISSUE THREAD

**Issue by Pathologic** [dmi3yy/modx.evo.custom#355]
Только пользователей смущает. Ее вполне может заменить плагин EvoModal.

**Comment by Fr3ddy7** [comment]
EvoModal больше нужен разработчику), блондинке лучше кнопочку для загрузки картинок или файлов, они с большим трудом находят её в самом редакторе

**Comment by dmi3yy** [comment]
Не соглашусь ;) 
Ибо им все равно нужно найти в редакторе как загрузить файлы и картинки. Без этого просто так загружать картинки толку мало 



Отправлено с iPhone

**Comment by Pathologic** [comment]
А каким образом можно загружать файлы через эту кнопку, там же только сниппеты, чанки и все такое?

**Comment by Pathologic** [comment]
Вообще этой кнопки вроде как уже и нет, видимо после вливания официальной ветки.

**Comment by dmi3yy** [comment]
Глянь тему MODxRE :) поймешь о каких кнопках речь. 
Да в сборке пока выпилил ибо надо плагином evoMODAL так приятней. А дальше посмотрим надо подумать как сделать что б всем удобно было

**Comment by Pathologic** [comment]
Чтобы минимально удобно было, нужно ее сделать отключаемой :smile:
