### ISSUE TITLE
передаются параметры из моделей

### ISSUE THREAD

**Issue by akosilov1** [dmi3yy/modx.evo.custom#356]
В частности модуль eLists

В консоли выдает ошибку CodeMirror, оказалось не хватает параметра indentWithTabs в настройках

**Comment by dmi3yy** [comment]
Есть такое до сих пор актуально пофиксю к след релизу

**Comment by dmi3yy** [comment]
Уф еле нашел ) 
пофиксил работать будет но подумаю как сделать коректней 
https://github.com/modxcms/evolution/issues/823
