### ISSUE TITLE
проблема с evoBabelLexicon

### ISSUE THREAD

**Issue by bloodywhat** [dmi3yy/modx.evo.custom#362]
Здраствуйте.
Поменял текст на главной странице с рус на украинский (текст) через TinyMCE. После начал сайт медленно грузиться и в окне evoBabelLexicon ошибка + preview не работает

Error : Undefined variable: langs
ErrorType[num] 	NOTICE[8]
File 	...manager/processors/execute_module.processor.php(73) : eval()'d code
Line 	45
Source 	evoBabelLexicon - Module

include_once(string $var1)
manager/index.php on line 572
evalModule(string $var1, array $var2)
manager/processors/execute_module.processor.php on line 60

Да, и могу ли я что-то исправить с праваит editor, я не админ.
Спасибо за внимание.

**Comment by dmi3yy** [comment]
Не передаются параметры с модуля в сниппет 
https://github.com/dmi3yy/modx.evo.custom/issues/356
скоро поправлю
