### ISSUE TITLE
Отключаются TV-параметры

### ISSUE THREAD

**Issue by foxcoonn** [dmi3yy/modx.evo.custom#365]
В последнее время начал замечать, что на новых проектах TV-параметры отключаются от шаблонов.

**Comment by Zlabst** [comment]
Если изменить шаблон, то нужно заново включать некоторые TV для этого шаблона. Закономерность не смог уловить

**Comment by bagi091** [comment]
Скорее всего закономерность в следующем. 
В новых версиях сборки при редактировании шаблона можно изменять список прикрепленных TV, и если вы, например, открыли шаблон для редактирования к которому было прикреплено 2 TV, отвлеклись и на новой вкладке привязали дополнительный TV к шаблону через редактирование TV параметров, а после всего этого сохранили шаблон, то у вас в результате будет только 2 прикрепленных TV

**Comment by dmi3yy** [comment]
ну да и это логично ибо в Шаблон не попал новый тв  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 6 сентября 2016 г. в 10:43, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
Согласен, бага в этом не вижу, это просто особенность
