### ISSUE TITLE
У кнопки "Просмотр" не генерируется ссылка

### ISSUE THREAD

**Issue by foxcoonn** [dmi3yy/modx.evo.custom#366]
1. Создаем ресурс
2. Сохраняем
3. Нажимаем кнопку "Просмотр ресурса"
В результате нас перекидывает на страничку типа:
http://АДРЕС САЙТА/.../ИДЕНТИФИКАТОР РЕСУРСА.html
вместо того чтоб сгенерировать ссылку через алиас.
Приходиться обновлять страницу в админке, чтоб сгенерировалась правильная ссылка.
Что очень тяжело объяснить менеджерам.

**Comment by dmi3yy** [comment]
Проверил на 8.1.3  все ок. 
после кнопки сохранить ссылка уже корректная, что в просмотре что в варианте сохранить и продолжить
