### ISSUE TITLE
Баг в работе phpthumb

### ISSUE THREAD

**Issue by Voxeler** [dmi3yy/modx.evo.custom#368]
Обнаружил баг в работе phpthumb:
Конструкция такая:
`<img src="[[phpthumb? &input=`[+image+]` &options=`w=300`]]"/>`
На выходе получаю превью-заглушку, вместо загруженной картинки:
`<img src="assets/cache/images/assets/snippets/phpthumb/300x-noimage.09a.png"/>`
Произвел рекомендации из этого топика:
`http://modx.im/blog/questions/724.html`
результат нулевой.
Чистка кеша, переустановка сниппета не помогла.
Сборка MODx 1.1-d8.0

**Comment by dmi3yy** [comment]
Все логично 

Нужно хотя бы проблел после ] или в идеале параметры в кавычки 

Отправлено с iPhone

**Comment by Voxeler** [comment]
Параметры в кавычках в оригинале.
Здесь редактор их удаляет, когда я использую вставку кода.
Я уже пробовал конструкцию из примера в сниппете:
[[phpthumb? &input=`[+image+]` &options=`w=150,h=76,far=C,bg=FFFFFF`]]
тупо копи-пастом с подстановкой своего TV.

Тот-же результат.

**Comment by bagi091** [comment]
Может глупость скажу, но все же. Такой плэйсхолдер точно существует? Если вы используете такой вызов в чанке DocLister и забыли указать параметр сниппета tvList='image' и tvPrefix='', то результат будет заглушка

**Comment by Voxeler** [comment]
Это обычный вызов phpthumb. Он должен работать даже с минимальными параметрами &options=w=150, если я не ошибаюсь.
Я пытаюсь понять, у меня траблы с настройками PHP на сервере или это баг в сборке.
В логах CMS никаких ошибок.
Провайдеры ничего толком не ответили. 
Стандартное: проблемы на стороне пользовательских скриптов.
В предыдущих сборках с аналогичными вызовами проблем не было.
