### ISSUE TITLE
Не работает MultiPhotos на версии 1.1-d8.0

### ISSUE THREAD

**Issue by wmlev** [dmi3yy/modx.evo.custom#369]
При редактировании ресурса не обрабатывается поле ресурса плагином MultiPhotos. В результате так и выводится textarea. Я так понимаю, что проблема с параметрами плагина так и не решена. По видимому именно они не читаются. 
[fix broken shared properties](https://github.com/dmi3yy/modx.evo.custom/commit/f5b1c91b7f086f02936502c1da74807b556d3998) - использовал данную правку. Не помогло!

**Comment by wmlev** [comment]
Обновил несколько сайтов до последней версии и теперь не знаю куда смотреть и что делать. Везде подобного рода проблемы. MultiPhotos слетел на всех сайтах.

**Comment by dmi3yy** [comment]
Обновитесь до версии 8.1.2 


Отправлено с iPhone

**Comment by dmi3yy** [comment]
Так же обноаите мультифотос. 

Отправлено с iPhone

**Comment by wmlev** [comment]
Я так понимаю, что версия 8.1.2 пока не существует. Ее нет на сайте modx.com.ua. Просто скачать архив с git? Но на сколько можно быть уверенным в стабильности?

**Comment by dmi3yy** [comment]
качать с гитхаба.  
На текущий момент она уже стабильней чем 8.0  
как раз собираю третий проект на ней полет нормальный. Как только будет минутка залью на modx.com.ua  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 9 сентября 2016 г. в 11:19, wmlev написал:

**Comment by dmi3yy** [comment]
переехало в тему не работает в 8.1.3 до след релиза проверю исправлю
