### ISSUE TITLE
Не работает KCFinder

### ISSUE THREAD

**Issue by Grinyaha** [dmi3yy/modx.evo.custom#370]
Только у меня в 8.1.2 не работает KCFinder и в дереве вверху нет иконок
1) manage files
2) manage images
3) сортировка
4) элементы

**Comment by dmi3yy** [comment]
ксфиндер иногда выделывается на некоторых хостингах из за настроек. никак не доберемся исправить.  

иконок в базовой теме и нет они есть в теме MODxRE  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 10 сентября 2016 г. в 01:09, Alexander написал:

**Comment by Grinyaha** [comment]
Вверху из этих 4 иконок работает только 1, это элементы.

**Comment by dmi3yy** [comment]
Ок проверю:) по файлменеджеру можно попробовать поставить elFinder  
https://github.com/Temus/elFinder


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 10 сентября 2016 г. в 01:26, Alexander написал:

**Comment by Grinyaha** [comment]
А как его ставить? мануала даже краткого нет :(

**Comment by dmi3yy** [comment]
Распаковать то что есть в папку текущего 
Manager/mediA/browser/mcpuk


Отправлено с iPhone

**Comment by Grinyaha** [comment]
Димка перегрузил сервак все заработало. Видимо ночью уже глаз замылился. Снимаю вопрос вощем))
