### ISSUE TITLE
YAMS - 404 ошибка

### ISSUE THREAD

**Issue by wmlev** [dmi3yy/modx.evo.custom#371]
После обновления одного из проектов до последней версии 8.1.2, сайт выдает 404 ошибку. Настройки YAMS не менялись. Просто было обновление с версии 8.0. Все вроде должно было работать, но что-то не так ((

**Comment by wmlev** [comment]
Поставил чистый движек версии 8.1.2 и установил YAMS. Изменил .htaccess в соответствии с настройками YAMS. И при переходе на сайт получаю ошибку 404. Может были какие-то изменения в данной версии, связанные с редиректами?

**Comment by wmlev** [comment]
Необходимо решение. В чем может быть полблема? В каком направлении копать? HELP.

**Comment by wmlev** [comment]
Относительно данного вопроса. Нет ни у кого идей?

**Comment by dmi3yy** [comment]
На офф в гитхаб писали что все ок должно работать 

Отправлено с iPhone

**Comment by xaos86** [comment]
В файле manager/includes/document.parser.class.inc.php стави в комент линию 1888 с "$_REQUEST['q'] = $_GET['q'] = $this->setRequestQ($_SERVER['REQUEST_URI']);". Это связано с дружественные URL

**Comment by dmi3yy** [comment]
Для работы с Yams необходимо отключить параметр seostrict в настройках ЧПУ 
ибо у Yams свои правила поэтому и конфликт
