### ISSUE TITLE
Куда делись сообщения в админке?

### ISSUE THREAD

**Issue by Grinyaha** [dmi3yy/modx.evo.custom#372]
Раньше были сообщения в даминке между пользователями, теперь их нет. Это фича или бага?

**Comment by wmlev** [comment]
У меня есть возможность отправлять сообщения и отображается в правом верхнем углу

**Comment by Grinyaha** [comment]
А у меня нету 0_0

**Comment by Grinyaha** [comment]
И ссылки помощь у меня тоже нет.

**Comment by wmlev** [comment]
В последнее время очень много проблем появилось. Многие модули перестали работать нормально. И бывают совсем не понятные вещи. Дмитрий делает очень хорошее дело поддерживаю modx и дорабатывая его. Надо как-то объединить усилия и помочь развивать движок.

**Comment by wmlev** [comment]
![clip2net_160911184350](https://cloud.githubusercontent.com/assets/1217971/18418467/bdd43ec0-784f-11e6-81c0-e479cf73f4d9.png)

**Comment by Grinyaha** [comment]
Понятно, это в скине MODxRE нет этих ссылок. Есть только в D3X

**Comment by dmi3yy** [comment]
Сейчас активно правят и офф версию 

Отправлено с iPhone

**Comment by dmi3yy** [comment]
С учетом что сообщениями пользуются крайне мало их урали с верхнего меню остались на главной в первом виджете :)
