### ISSUE TITLE
В DocManager пропала сортировка пунктов меню

### ISSUE THREAD

**Issue by achekalin** [dmi3yy/modx.evo.custom#373]
В /assets/modules/docmanager/templates/main.tpl вообще пропал блок, отвечающий за вывод вкладки про сортировку:

```
<div class="tab-page" id="tabSortMenu">
  <h2 class="tab">[+lang.DM_sort_menu+] </h2>
  <script type="text/javascript">tpResources.addTabPage(document.getElementById("tabSortMenu"));</script>
[+view.sort+]
</div>
```

Причина такого шага непонятна.

**Comment by dmi3yy** [comment]
Это вынесли в контекстное меню в дереве документов 

Отправлено с iPhone
