### ISSUE TITLE
Плагин MultiPhotos не работает в админке (ver. 1.1-d8.1.3)

### ISSUE THREAD

**Issue by wmlev** [dmi3yy/modx.evo.custom#374]
На странице документа не появляется форма для загрузки фото, а так и остается текстовое поле.
![clip2net_161004074523](https://cloud.githubusercontent.com/assets/1217971/19062900/8bb4c0c2-8a06-11e6-9c1c-37c8da5d184b.png)

**Comment by dmi3yy** [comment]
Обновите сам плагин в него недавно вносили изменение

Отправлено с iPhone

**Comment by dmi3yy** [comment]
А вообще рекомендую перейти на multiTV 
Ибо мультифото давно не поддерживается

Отправлено с iPhone

**Comment by dmi3yy** [comment]
Неа не работает и ошибок смотрю нет
https://github.com/extras-evolution/MultiPhotos/issues/2 вынес сюда задачку 
если кто починет то будет ок. Но  в целом считаю что устарело.
