### ISSUE TITLE
Управление поддоменами в одной админке (города-поддомены)

### ISSUE THREAD

**Issue by bagi091** [dmi3yy/modx.evo.custom#375]
[Тут](http://modx.im/blog/addons/2312.html) приводиться хорошая инструкция по тому как реализовать данный функционал с помощью modx, однако после  недавнего коммита (e2ec831a145ecea95fdb205a526b32fc12d7656e), эта инструкция не помогает в связи с тем что get параметр q, начал формироваться в DocumentParser.

**Comment by dmi3yy** [comment]
Зачем так сложно все реализовуется куда проще  не нужно доп событие для этого дела : )

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 18:18, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
через .htaccess нельзя, так как GET[q] потом модифицируется. можно было черкз событие notFound, но в этом случае нужно больше проверок делать и есть вероятность вызова мобытия notFound дважды при запросе страниув, да и до вызова этого события выполняется больше кода, который время занимает, пусть и мало, но все же. Или есть еще вариант?))

**Comment by dmi3yy** [comment]
Я мульти сайтовость так делаю:  
http://prnt.sc/ct03oq

Все банально проверкой что у нас в http_host  

далее все нужные домены поддомены подключаем настройки домена как алиасы и получаем что надо :)  
и никаких заморочек  с плагинами и переделкой урл :)  

уже штук 5 сайтов сделал таким образом и все ок.  

А с решением по ссылке были проблемы с настройкой:  
- ajax  
- sitemap  
- пагинации Ditto  
- хлебных крошках  

приходилось пилить снипеты что  б оно коректно срабатывало.  

Да можно еще 1 событие подключить но как по мне это не сильно целесообразно если есть более простые решения   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 19:52, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
простите а точно тот скиншот прикрепили?))

**Comment by dmi3yy** [comment]
нет :)  
http://take.ms/1igBN


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 20:00, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
Хм.. А я что-то не могу разобрать, где это вызывается.

**Comment by dmi3yy** [comment]
Это сниппет вызывается на станичке и отдает то что надо в зависимости от адреса по которому заходим  

так же можно отдавать разные документы и параметры  
у меня выдаются разные новости и разные контентакты + разные стили но при этом  
каталог единый  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 20:32, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
А какая версия modx используется на этом сайте?

**Comment by dmi3yy** [comment]
Там старая но 7.1.2 если не ошибаюсь но будет работать и на последней ибо там вообще нет привязки к переменным.  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 20:41, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
А как происходит распознавание из какой папки брать документ?

**Comment by dmi3yy** [comment]
Мы указываем в  сниппете скринт которого я скинул )

типа  
[!Domen? &type=`catalogID`!]


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 20:43, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
Просто на версиях после 2 сентября конструкция в htaccess вида
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{HTTP_HOST} ^([a-zA-Z\-]+).site\-example\.com$ [NC]
RewriteRule ^(.*)$ index.php?q=/%1/$1 [L,QSA]

не работает

**Comment by bagi091** [comment]
А в админке есть папки te, dp, kiev и так далее? которые содержат отличающиеся страницы (например sitemap.xml)

**Comment by dmi3yy** [comment]
Да все верно там папки и указанно откуда брать  
http://take.ms/jRw2U

Таким образом получается все приятней логичней и меньше кода и багов  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 20:47, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
а в этом проекте файл htaccess получается не изменялся?

Кажется я уже понял в чем дело)) Возможно у меня задача другая стояла (или я уже устал и просто ничего не понимаю).
Мне было нужно, чтобы обращении к поддомену, например n1.example.com выводилась промо страничка example.com/parent/n1.html
а при обращении к n1.example.com/news.html выводилась информация со страницы example.com/parent/n1/news.html

При этом у всех этих страниц могут быть разные шаблоны и весь мой плагин выглядит так 

```
$requestQ = isset($requestQ) ? $requestQ : null;
$main_host = 'example.com';
$request_host = $_SERVER['HTTP_HOST'];
$request_uri = $_SERVER['REQUEST_URI'];
	
if( $request_host != $main_host ){
	$url = 'parent/'.substr($request_host,0,strpos($request_host,'.'.$main_host));
	$url = empty($requestQ) ? $url.'.html' : $url.'/'.$requestQ;
		
	$e->_output = $url;
}
```

**Comment by bagi091** [comment]
Получается в вашем случае при обращении к странице новости на любом из доменов выводиться одинаковая страница (с одинаковым id)
а в моей задаче, выводиться разные страницы в зависимости от

**Comment by dmi3yy** [comment]
Да но новости то все разные:) что и требуется :) не вижу не соответствия с поставленной задачей)  






--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 21:03, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
))) а шаблоны нет

**Comment by dmi3yy** [comment]
А шаблоны тоже могут быть разные не вижу проблемы :)  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 21:08, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
)) но для этого нужно писать плагин?

**Comment by dmi3yy** [comment]
Зачем ?
все через тот же сниппет решается в шаблоне какой нужно вывод  
или делаются разные странички новостей по папкам и номер id в меню выводиться через сниппет  

банально если все разложенно по папкам то нам достаточно заменить стартовую страничку  
на главной делаем сниппет который отадет нужные внутренности и все  
делов на 1 простой сниппет вместо нескольких плагинов которые выполняют лишнюю работу по парсингу  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 21:11, Aliaksandr Lakhvich написал:

**Comment by dmi3yy** [comment]
[!Wayfinder? &startId=`[!domen? &type=`homeid`!]`!] и все  

или есть апишка вернуть контент нужной странички в себя же ) если и гравные отличаются )
тогда да 1 мелкий плагин но только для редиректа на нужную страничку  

вообщем мультисайтовость не проблема без доп события и решения Веббера  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 21:14, Lukianenko Dmytro написал:

**Comment by bagi091** [comment]
да, я уже так и подумал))
спасибо за беседу, попробую реализовать свою задачу через ваш способ

**Comment by dmi3yy** [comment]
Если что пишите  
но лучше в почту сразу :)  
dmi3yy@gmail.com  
подскажу)


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 12 октября 2016 г. в 21:17, Aliaksandr Lakhvich написал:

**Comment by bagi091** [comment]
ок)

**Comment by dmi3yy** [comment]
Исправил там они загнались по фиксту одного комита в итоге поломали :) 
теперь работает
