### ISSUE TITLE
Wayfinder не работает для ресурсов в групах

### ISSUE THREAD

**Issue by xaos86** [dmi3yy/modx.evo.custom#379]
У меня на проекте ести пару ресурсов которые находится в групе, и когда ползаватели зашол, то он должен их видети, код же: [[wayfinder? &startId=`22`]], это група имено для этого полизавателя.
Но никак, я знаю што все работает, потому што ести очени похожии проект где всео работает, но взят отсюда с версии апреля. Помогите пожалуста

**Comment by xaos86** [comment]
Што никто не встречался с этим или никто не знает, если не обиснил нормалино мне лехче на англиском.

**Comment by dmi3yy** [comment]
Use DLBuildMenu 

new issues plz write here 
https://github.com/evolution-cms/evolution/
