### ISSUE TITLE
Плагин MultiPhotos перестал работать в новых сборках.

### ISSUE THREAD

**Issue by doggydogg-spb** [dmi3yy/modx.evo.custom#380]
После обновление до d8.1.3 и d8.1.4 на многих проектах перестал работать плагин MultiPhotos.

**Comment by dmi3yy** [comment]
Уже писал что этот плагин давно не поддерживается и нужно использовать MultiTV 


Отправлено с iPhone

**Comment by doggydogg-spb** [comment]
А как безболезненно перейти на старых проектах с MultiPhotos на MultiTV?

**Comment by dmi3yy** [comment]
проще всего написать простой сниппет который сконвертит из масива multiPhotos в масив multiTV  
там поидее работы на 15-20 минут ну а на фронте поменять вывод вообще не проблема.  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 25 октября 2016 г. в 22:14, doggydogg написал:

**Comment by dmi3yy** [comment]
Нашел простой фикс :) 
просто заполните  все поля 

не только список id но и роли (1,2,3) и список шаблонов после чего начинает работать :) 
http://prnt.sc/czl0s4

**Comment by doggydogg-spb** [comment]
Большое спасибо! Значит пока ещё поработает MultiPhotos... А не знаете, как вернуть отображение эскизов?

**Comment by dmi3yy** [comment]
http://modx.im/blog/fast-solution/4762.html#comment37827

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 15:11, doggydogg написал:

**Comment by dmi3yy** [comment]
пофиксили багу с параметрами с картинкой надо еще залить

**Comment by dmi3yy** [comment]
Все все пашет как надо 
сейчас опубликую релиз 
http://take.ms/lQyZC
