### ISSUE TITLE
Галка Дочерние ресурсы отображаются в дереве не работает

### ISSUE THREAD

**Issue by inscriptible** [dmi3yy/modx.evo.custom#389]
Собственно обновился до последней версии и перестала работать эта галка. Убираешь ее, но дочерние документы все равно видны в дереве
![2016-11-09_09-47-12](https://cloud.githubusercontent.com/assets/917761/20127521/2616db12-a66a-11e6-93f0-5ef21b51d963.png)

**Comment by dmi3yy** [comment]
Да это выключили ибо теперь не тормозит когда дочерних документов больше 200

Отправлено с iPhone

**Comment by inscriptible** [comment]
А как все таки сделать чтобы работало? (то есть список ресурсов не в дереве а именно списком)

**Comment by dmi3yy** [comment]
Там хак в файлике manager/frames/node.php 

Надо поставь условие на эту галку сейчас в отпуске потому точные строки сейчас не подскажу

Отправлено с iPhone

**Comment by dmi3yy** [comment]
Сделали теперь будет в 1.3.0 и будет работать
