### ISSUE TITLE
Баг с перемещенными полями 1.2-d8.1.5

### ISSUE THREAD

**Issue by Typodin** [dmi3yy/modx.evo.custom#390]
При создании новой вкладки, с последующим созданием в ней новых секций и полей (типа так: http://joxi.ru/KAxVoqxI4zkDKm ) при первом открытии ресурса после создания или после создания нового документа все поля недоступны для редактирования. После пересохранения страницы все кроме RichText работает. 

В предыдущей версии баг отсутствует.

Баг наблюдаю в Chrome. Mozilla работает нормально.

**Comment by dmi3yy** [comment]
Отправь плз в манагеманагер 
Там Илиас как раз пилит сейчас 

Отправлено с iPhone

**Comment by Typodin** [comment]
Окай)
