### ISSUE TITLE
Создание нового веб-юзера

### ISSUE THREAD

**Issue by Grinyaha** [dmi3yy/modx.evo.custom#392]
При создании нового веб-юзера из админки и выбора пункта "отправить пароль на емайл" выдается такая ошибка
Parse error: syntax error, unexpected ')' in E:\OpenServer\domains\site.ru\manager\includes\extenders\modxmailer.class.inc.php on line 116

**Comment by dmi3yy** [comment]
Напишите плз в офф репозитории на английском. А то я еще неделю а отпуске там быстрее пофиксят

Отправлено с iPhone

**Comment by Grinyaha** [comment]
Димка, дай ссылку куда писать.

**Comment by dmi3yy** [comment]
Офф ремозиторий 
Modxcms/evolution

Отправлено с iPhone
