### ISSUE TITLE
В последних версиях OnManagerWelcomeHome баг или фича?

### ISSUE THREAD

**Issue by radist** [dmi3yy/modx.evo.custom#394]
На этом событии висел плагин ShopkeeperIcon.

Теперь иконка улетела куда то. Это так задумано или случайно получилось?

![3253452345](https://cloud.githubusercontent.com/assets/106756/20564828/fd6f04fa-b19f-11e6-8e37-8cea850045c8.jpeg)

**Comment by dmi3yy** [comment]
Там сейчас совершенно другая главная страничка в админке потому  там фича но старые  плагины нужно будет поправить  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 23 ноября 2016 г. в 17:11, radist написал:

**Comment by radist** [comment]
Как ее увидеть? Я обновил на последнюю версию. Тему еще надо поменять? А со старой дефолтной темой что?

**Comment by dmi3yy** [comment]
Обновить тему на modxre2  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 23 ноября 2016 г. в 17:17, radist написал:

**Comment by dmi3yy** [comment]
Фича там сейчас на это событие вызывается добавление виджетов :) 
сейчас разберусь с тикетами и засяду релиз писать что где куда как
