### ISSUE TITLE
Не работает кнопка Сохранить при редактировании чанков/ресурсов

### ISSUE THREAD

**Issue by doxadoxa** [dmi3yy/modx.evo.custom#397]
Не работает кнопка "Сохранить" в админке в некоторых разделах. Скрин console прикладываю. В чем может быть проблема? Версия от 28 октября. 

Объект document.muted.save выдает undefined.

![image](https://cloud.githubusercontent.com/assets/669799/20625064/d4cc0fc4-b321-11e6-9693-5757658b1d3a.png)

**Comment by dmi3yy** [comment]
Обновите на гит версия свежее есть  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 25 ноября 2016 г. в 15:15, Taras Dovgal написал:

**Comment by doxadoxa** [comment]
Обновил на двух сайтах сборку с гита, та же проблема

**Comment by dmi3yy** [comment]
За сегодня обновил уже 3 сайта все ок везде сохраняет  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 25 ноября 2016 г. в 17:01, Taras Dovgal написал:

**Comment by doxadoxa** [comment]
Интересно, видимо что-то не так делаю. А файл конфига с официальной сборкой совместим с вашей? и тот же вопрос по бд.

**Comment by dmi3yy** [comment]
Да, они полностью одинаковы отличия в настройках и наборе елементов

Отправлено с iPhone

**Comment by doxadoxa** [comment]
Проблема была со старым TinyMCE, который при обновлении почему-то оставался включенным. Поэтому закрываю.
