### ISSUE TITLE
Неверное условие для блокировки документа

### ISSUE THREAD

**Issue by radist** [dmi3yy/modx.evo.custom#398]
https://github.com/dmi3yy/modx.evo.custom/blob/5dc0b3557b43cb12716adc481d81beddb20bc991/manager/includes/active_user_locks.php#L20

Я так понимаю надо инвертировать условие. Иначе документ не будет блокироваться никогда.

**Comment by dmi3yy** [comment]
Напиши плз в Офф ветку там Deesen это пилит и сейчас еще допиливать будет мы там логику еще поменяем  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 25 ноября 2016 г. в 16:16, radist написал:
