### ISSUE TITLE
Непонятная работа админки и подключаемых плагинов по https 

### ISSUE THREAD

**Issue by sazanof** [dmi3yy/modx.evo.custom#399]
Приветствую! Возможно не только у меня наблюдается в МЕНЕДЖЕРЕ проблема:
Даже если указать везде подключение по https:// в  [+site_url+] передается всегда http://
Помогает только замена
// assign site_url
$site_url= ((isset ($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on') || $_SERVER['SERVER_PORT'] == $https_port) ? 'https://' : 'http://';
на
$site_url= ((isset ($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on') || $_SERVER['SERVER_PORT'] == $https_port) ? 'https://' : 'https://';
А сайт загружен по https

**Comment by dmi3yy** [comment]
А [+site_url+] - нет такого

есть [(site_url)]  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 29 ноября 2016 г. в 11:56, Михаил написал:

**Comment by sazanof** [comment]
Прошу прощения
да, опечатался 
([site_url]) и $modx->config('site_url'); если не ошибаюсь

**Comment by radist** [comment]
Посмотрите дамп массива $_SERVER часто бывает что хостинг настроен криво и порт по https там будет 80.

**Comment by sazanof** [comment]
Спасибо, Вы абсолютно правы!
