### ISSUE TITLE
Не работает &math в сниппете if

### ISSUE THREAD

**Issue by wmlev** [dmi3yy/modx.evo.custom#402]
[[ if? &is=`[+ditto_iteration+]+1:%:5` &then=`<div class="clear"></div>` &math=`on` ]]
Просто сделал сегодня обновление до последней версии на одном из сайтов. Поставил прежний вариант, сниппета... все работает.

**Comment by dmi3yy** [comment]
а можно пример  вызова

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 5 декабря 2016 г. в 12:45, wmlev написал:

**Comment by wmlev** [comment]
написал выше

**Comment by dmi3yy** [comment]
А все увидел ок глянем знаю где  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 5 декабря 2016 г. в 12:47, wmlev написал:
