### ISSUE TITLE
Nesting level too deep

### ISSUE THREAD

**Issue by ivan-smirnyagin-1** [dmi3yy/modx.evo.custom#406]
Nesting level too deep
![2016-12-17_01-35-58](https://cloud.githubusercontent.com/assets/24613445/21277654/4fce5bfe-c3f9-11e6-92a7-9489bac89708.png)
![2016-12-17_01-36-22](https://cloud.githubusercontent.com/assets/24613445/21277655/4fcf6396-c3f9-11e6-8820-89829704e4a7.png)

**Comment by dmi3yy** [comment]
set form 20 to 200 now work fine
