### ISSUE TITLE
Плагин bDebug

### ISSUE THREAD

**Issue by ivan-smirnyagin-1** [dmi3yy/modx.evo.custom#407]
Плагин bDebug не показывает что страницы кэшируются, не работает кэширование на всем сайте.
Так же вывод параметра аналогично:
Memory: [^m^], MySQL: [^qt^], [^q^] request(s), PHP: [^p^], total: [^t^], document retrieved from [^s^].
![2016-12-17_01-43-40](https://cloud.githubusercontent.com/assets/24613445/21277897/4aa75904-c3fa-11e6-94de-d63c41091923.png)

**Comment by dmi3yy** [comment]
А галочки у документов стоят ? что они кешируемые ?  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 16 декабря 2016 г. в 22:44, ivan-smirnyagin-1 написал:

**Comment by ivan-smirnyagin-1** [comment]
Да, везде отмечено, снятие галочек тоже самое.

**Comment by dmi3yy** [comment]
Проверил работает как положено
