### ISSUE TITLE
новый веб пользователь - ошибка

### ISSUE THREAD

**Issue by ivan-smirnyagin-1** [dmi3yy/modx.evo.custom#408]
При создание в админки нового пользователя, возникает ошибка. Пользователь создается но на этапе регистрации его показывает ошибку. 
Пользователи --> Управление веб-пользователями --> новый веб пользователь 
![2016-12-17_01-50-54](https://cloud.githubusercontent.com/assets/24613445/21278163/744a795c-c3fb-11e6-95cc-753f98812e5d.png)
![2016-12-17_01-51-16](https://cloud.githubusercontent.com/assets/24613445/21278170/76fd4b2a-c3fb-11e6-84b9-532758afb63c.png)

**Comment by dmi3yy** [comment]
у вас не все файлы есть попробуйте перезаписть ибо такой ошибки не должно быть  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 16 декабря 2016 г. в 22:53, ivan-smirnyagin-1 написал:

**Comment by ivan-smirnyagin-1** [comment]
пробовал, текущую сбору скачал вот щас и поставил, тоже самое (((
может дело в openserver
![2016-12-17_01-57-54](https://cloud.githubusercontent.com/assets/24613445/21278311/50f5b5f6-c3fc-11e6-8480-4dbdaaeab183.png)

**Comment by dmi3yy** [comment]
Локально на винде вообще не проверяю но работать должно  
на сервере все ок вот как раз собираю сайт  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 16 декабря 2016 г. в 22:59, ivan-smirnyagin-1 написал:

**Comment by ivan-smirnyagin-1** [comment]
понял вас, спасибо, значит дело в openserver
