### ISSUE TITLE
@INCLUDE - не работает

### ISSUE THREAD

**Issue by ivan-smirnyagin-1** [dmi3yy/modx.evo.custom#409]
Подключение файлов в Шаблон при помощи @INCLUDE - не работает.
<code>@INCLUDE:theme/1.html</code>
<code>@INCLUDE:assets/templates/mydesign/template.html</code>

Пробовал добавить код:
1. в саму страницу при редактировании
2. в шаблон
3. в чанк
![2016-12-17_02-08-31](https://cloud.githubusercontent.com/assets/24613445/21278646/37bb7e20-c3fe-11e6-9b7b-5bcd753fd419.png)
![2016-12-17_02-08-45](https://cloud.githubusercontent.com/assets/24613445/21278647/37c18568-c3fe-11e6-831f-00f85ebe32ed.png)

**Comment by dmi3yy** [comment]
это лучше все писать сейчас в офф репозиторий :)  
так быстрее будет это этот код не я добавлял как по мне  он вообще не нужен как и phx и @IF ))  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 16 декабря 2016 г. в 23:12, ivan-smirnyagin-1 написал:

**Comment by ivan-smirnyagin-1** [comment]
понял спасибо ;)

**Comment by zabudkin** [comment]
Проблему решили?

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/27
