### ISSUE TITLE
eform, SMTP Connect failed

### ISSUE THREAD

**Issue by doxadoxa** [dmi3yy/modx.evo.custom#414]
Перепроверил все: не работает никак. Собственно пишет то, что в сабже. Оф ветка работала с теми же настройками отлично, чистый скрипт на phpmailer тоже работает без нареканий. 
Обновил один из сайтов на последнюю версию сборки с гита: сервак зависает на 3-5 минут и выдает в логи: Error while sending QUERY packet.
Пробовал версии PHP 5.6, 7.0. Openssl, fsockopen и прочее работает (лежит на разных хостингах: timeweb, infobox, valuehost и т.д.)
Функцию mail дергает на ура без проблем.

**Comment by doxadoxa** [comment]
Решение не появилось?

**Comment by dmi3yy** [comment]
проверьте просто параметры  подключения что б параметр from был такой же как и в авторизации smtp

От 14 января 2017 г. в 22:40:48, Taras Dovgal (notifications@github.com) написал:

Решение не появилось?

**Comment by dmi3yy** [comment]
fixed id 1.2.2
