### ISSUE TITLE
Ошибка, если в URL $_GET['q'] является массивом

### ISSUE THREAD

**Issue by Serg28** [dmi3yy/modx.evo.custom#418]
Если добавить в урл `?q[]=  (т.е. q сделать массивом), появляется ошибка. Как вариант решения, предлагаю в файле protect.inc.php после 
`// Null is evil
if (isset($_SERVER['QUERY_STRING']) && strpos(urldecode($_SERVER['QUERY_STRING']), chr(0)) !== false)
die();`

добавить 
`if (is_array($q)) die();`

**Comment by dmi3yy** [comment]
Исправили 
новые тикеты создаем тут: 
https://github.com/evolution-cms/evolution/
