### ISSUE TITLE
Определение протокола (http/https)

### ISSUE THREAD

**Issue by buzzhunter1994** [dmi3yy/modx.evo.custom#420]
Столкнулись с проблемой после обновления программного обеспечения сервера, CMS Modx Evo не правильно определяет протокол (http/https) при установленном ssl сертификате
мы решили проблему добавлением следующего кода в файл '/manager/includes/config.inc.php'

// assign site_url
$site_url= ((isset ($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on') || $_SERVER['SERVER_PORT'] == $https_port) ? 'https://' : 'http://';

$secured = (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https');
// assign site_url
$site_url= ((isset ($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on') || $_SERVER['SERVER_PORT'] == $https_port || $secured ) ? 'https://' : 'http://';

**Comment by zabudkin** [comment]
А Вы в настройках-то указали, что Ваш сайт httpS ?

**Comment by buzzhunter1994** [comment]
конечно указали

**Comment by dmi3yy** [comment]
Странно за последнее время перевел на https много сайтов проблем не было

Отправлено с iPhone

**Comment by buzzhunter1994** [comment]
проблема в том что не все серверы возвращают $_SERVER['HTTPS'] корректно, а $_SERVER['HTTP_X_FORWARDED_PROTO'] заполнен как положено, столкнулись именно при переносе сайтов на другой сервер

**Comment by dmi3yy** [comment]
Ага понял тогда логично

Отправлено с iPhone

**Comment by buzzhunter1994** [comment]
можно ждать в следующем релизе?

**Comment by dmi3yy** [comment]
Да .

Будет к концу месяца как вернусь с отдыха

Отправлено с iPhone
