### ISSUE TITLE
Не сохраняет чанки

### ISSUE THREAD

**Issue by Aligan** [dmi3yy/modx.evo.custom#423]
Достался сайт на правки. Проблема в том что в админке не сохраняются чанки. Нажимаешь сохранить, перезагружается фрейм и все, все остается также.

**Comment by Aligan** [comment]
Выяснил что срабатывает ошибка $modx->webAlertAndQuit("Chunk not found for id '{$id}'.");
Вероятно не передается созданные ID через REQUEST['id'];
Может у кого было такое?

**Comment by dmi3yy** [comment]
Проверь  доп плагины 


Отправлено с iPhone

**Comment by Aligan** [comment]
Дмитрий, я все плагины отключил. 
В файле save_htmlsnippet.processor.php  50 строчка там переменная $newid возвращает 0.
```
$newid = $modx->db->insert(
			array(
				'name'    => $name,
				'description' => $description,
				'snippet' => $snippet,
				'locked' => $locked,
				'category' => $categoryid,
                                'editor_type' => $editor_type,
                                'editor_name' => $editor_name
			), $modx->getFullTableName('site_htmlsnippets'));

			// invoke OnChunkFormSave event
			$modx->invokeEvent("OnChunkFormSave",
									array(
										"mode"	=> "new",
										"id"	=> $newid
									));
```
Я так понял

**Comment by Aligan** [comment]
newid = $modx->db->insert как проверить  что этот метод отработал. Т.е. как можно сделать доп проверку на ошибку, может он не может запись создать

**Comment by dmi3yy** [comment]
Недавно помогал с подобным бороться проверьте что б insert у вас все поля совпадают как надо. ибо если аписываете поле которого нет в базе может просто ничего не вернуть



От 28 февраля 2017 г. в 10:32:51, Aligan (notifications@github.com) написал:

newid = $modx->db->insert как проверить что этот метод отработал. Т.е. как можно сделать доп проверку на ошибку, может он не может запись создать

**Comment by Aligan** [comment]
Да, спасибо. Почему-то в таблице отсутствовале поле editor_name
