### ISSUE TITLE
Пропадают назначенные TV параметры

### ISSUE THREAD

**Issue by nartzis** [dmi3yy/modx.evo.custom#424]
Тема обсуждается тут
http://modx.im/blog/questions/4626.html

Если открыть шаблон в одном окне, а в другом окне создать TV параметр и назначить его для шаблона, то при сохранении шаблона в первом окне привязка TV параметра пропадает. 

Это связанно с тем, что теперь вторая вкладка шаблона содержит активный список TV параметров, и связи с ними пересоздаются каждый раз.

**Comment by webber12** [comment]
А что не так? В одной вкладке открыли список TV, создали новый, прикрепили к нему шаблон, сохранили. В это время во второй вкладке в открытом шаблоне этот TV не отмечен - при сохранении это идентично тому, что вы второй раз открыли шаблон и убрали птичку (удалили привязку TV к шаблону).

**Comment by nartzis** [comment]
Механизм понятен - к нему нет вопросов.
Но для работы, согласитесь, это не удобно.
Может это никто никогда не исправит, но как фиксация пожелания от сообщества может быть в качестве issue

**Comment by webber12** [comment]
Я, постоянно пользуясь Manage TVs on Template, наоборот, нахожу его весьма удобным. Просто дело привычки. А вот при создании шаблона переназначить ему нужные TV намного проще, чем потом каждый TV лезть редактировать. Тут же тоже можно сказать примерно следующее: "открыл в двух окнах одно TV потом в одном окне отметил шаблон, сохранил, а во втором окне не отметил и сохранил. В итоге - TV к шаблону не привязан"

**Comment by nartzis** [comment]
Об одних и тех же
Тут думаю дело привычки, и можно всё оставить как есть

Новая вкладка редактирования TV параметров весьма удобна

Но если при сохранении можно будет удалять связи только с теми TV параметрами, которые были загружены в эту вкладку, и не трогать связи с TV параметрами созданными после открытия шаблона, это было бы самым оптимальным вариантом, как мне кажется.

**Comment by Aharito** [comment]
Ну что ж, значит придется мне быть внимательнее и не торопиться при задании ТВ.
