### ISSUE TITLE
Cookie c именем id сбивают весь сайт

### ISSUE THREAD

**Issue by cabra** [dmi3yy/modx.evo.custom#429]
Если создать на сайте куку с именем "id" и присвоить ей числовое значение, то админка сходит с ума и главная тоже - они берут этот параметр как номер страницы. Пытаешься зайти на главную, а тебя перекидывает на страницу с id куки. 
Стоит версия 1.1-d8.0. Не знаю, исправлена ли в следующих версиях эта бага...

**Comment by dmi3yy** [comment]
Просьба писать тикеты тут: 
https://github.com/evolution-cms/evolution/

Создавать куку с системным полем не совсем логично так же как использовать $_GET  id или q
и хотеть что б они работали как вам надо :)
