### ISSUE TITLE
Перестала работать проверка на пустоту для cfg_

### ISSUE THREAD

**Issue by Typodin** [dmi3yy/modx.evo.custom#431]
Версия 1.2.1-d9.1.1 Перестала работать проверка на заполненность для параметров которые вызываются с помощью плагина CfgTv. На предыдущих версиях работало все нормально.

Пример проверки:

`[[if? &is=`[(cfg_time)]:!empty:` &then=`[(cfg_time)]`]]`

**Comment by dmi3yy** [comment]
проблема была с : в параметре :) а это разделитель по умолчанию
