### ISSUE TITLE
В разделе "Отчеты- расписание сайта" неправильно сортированы события

### ISSUE THREAD

**Issue by Watslock** [dmi3yy/modx.evo.custom#433]
Подраздел "События, связанные с публикацией ресурсов."

События сортируются по ... числу в месяце, но не по дате целиком..

т.е. это выглядит так:
	06-05-2017 08:12:00
	12-04-2017 00:24:00
	14-05-2017 08:10:00
	20-04-2017 08:11:00
	23-05-2017 08:12:00
	28-04-2017 08:11:00

май и апрель перемешаны... 

![2017-04-06_16-22-31](https://cloud.githubusercontent.com/assets/8936579/24756257/c5b6c8e0-1ae5-11e7-8e57-a07a2aceb723.png)

**Comment by dmi3yy** [comment]
Перенес сюда https://github.com/modxcms/evolution/issues/1297
проще стразу там писать можно на русском ) 
все равно  это глобальная бага и я веду 2 ветки
