### ISSUE TITLE
Тип содержимого application/json - не отключаются Friendly URLs

### ISSUE THREAD

**Issue by lyolkinn** [dmi3yy/modx.evo.custom#435]
Тип содержимого application/json, псевдоним оканчивается на .json, - но в конце добавляется .html . 
Пример: http://modxite.ru/filterjs-json.json - не работает, http://modxite.ru/filterjs-json.json.html - работает. 
С text/javascript (псевдоним оканчивается на .js) такой проблемы нет: http://modxite.ru/filterjs-js.js

**Comment by dmi3yy** [comment]
Я видел в офф репозитории вопрос можно не дублировать 
Надо в парсере добавить и json в исключения сделаю в след релизе 


Отправлено с iPhone
