### ISSUE TITLE
Не срабатывает настройка «Название ресурса в дереве»

### ISSUE THREAD

**Issue by sbWebber** [dmi3yy/modx.evo.custom#436]
Не срабатывает настройка «Название ресурса в дереве». Что бы не устанавливал, всё равно в дереве выводится [*pagetitle*].

В файле /manager/frames/nodes.functions.inc.php поправил строку 68. Заменил:
`$nodeNameSource = $_SESSION['tree_nodename'] == 'default' ? $modx->config['resource_tree_node_name'] : $_SESSION['tree_nodename'];`

на
`$nodeNameSource = (($_SESSION['tree_nodename'] == 'default') || ($_SESSION['tree_nodename'] == '')) ? $modx->config['resource_tree_node_name'] : $_SESSION['tree_nodename'];`

Не уверен, что внес правку в нужном месте, но всё же помогло. =)

**Comment by dmi3yy** [comment]
Перепроверил все рабоатет как надо 
из настроек берется если тут : http://take.ms/ZEJGz стоит по умолчанию и все ок
