### ISSUE TITLE
[решено]Баг с включенным ElementsInTree

### ISSUE THREAD

**Issue by F1fanatik** [dmi3yy/modx.evo.custom#437]
при включенном ElementsInTree так кажет http://images.vfl.ru/ii/1492167235/2312f733/16855213.jpg 
при выключенном норм..

**Comment by EGO7000** [comment]
Баг подтверждаю, проблема в том, что в файле /install/assets/plugins/ElementsInTree.tpl в строке записано свойство по умолчанию как `<i class='fa fa-sitemap'></i>`, но при установке, видимо парсер съедает первую кавычку и остаётся только **<i class=**. Фиксится очень просто - в конфигурацию плагина нужно в разделе **Tree Tab Title** записать исходное значение, т.е. `<i class='fa fa-sitemap'></i>`

**Comment by dmi3yy** [comment]
Так не закрывай пока в коде ж не поправили еще

Отправлено с iPhone

**Comment by dmi3yy** [comment]
fix but hardcode 
https://github.com/dmi3yy/modx.evo.custom/commit/320365047d0c00bb00175580bcfab9843527aed6
