### ISSUE TITLE
Сохранение плагинов по Ctrl+S

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#448]
Выскакивает сообщение с вопросом уйти и потерять данные или остаться и это значит, что никак данные уже не сохранить. Приходится копировать наиболее весомые значения полей, перезагружать фрейм, возвращать их на место и стараться не нажать снова Ctrl+S :)

**Comment by dmi3yy** [comment]
1.3.0b. работает как надо
