### ISSUE TITLE
Кастомный логотип

### ISSUE THREAD

**Issue by sazanof** [dmi3yy/modx.evo.custom#461]
На сколько полезен будет функционал установки своего логотипа? Например вывести его в [(site_logo)] и в конфигурации сделать возможность его выбора, да так, чтобы при входе в админку login_logo менялось на выбранный логотип.
![-1](https://cloud.githubusercontent.com/assets/3595562/26571777/112db3b0-4520-11e7-8f76-62ef5c37743e.jpg)

**Comment by dmi3yy** [comment]
В целом полезно но тут есть вопрос в том что менеджерам доступ в системные настройки лучше не давать тоесть это лого для странички входа будет и админки а на фронт если надо лучше использовать отдельно

Отправлено с iPhone

**Comment by sazanof** [comment]
Да, для админки и для стр входа

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/20
