### ISSUE TITLE
Контейнер содержащий дочерние ресурсы

### ISSUE THREAD

**Issue by ivan-smirnyagin-1** [dmi3yy/modx.evo.custom#462]
Контейнер содержащий дочерние ресурсы не показывает в раскрывающемся списке вложенные в него другие контейнеры. Не отображается раскрывающиеся папка.
![2017-05-30_15-19-18](https://cloud.githubusercontent.com/assets/24613445/26578978/6a1f3356-454b-11e7-8175-0970df548ac7.jpg)

**Comment by dmi3yy** [comment]
Поставьте галочку регистрировать посещения в настройке контейнера и будет отображаться все

**Comment by ivan-smirnyagin-1** [comment]
Спасибо!
