### ISSUE TITLE
фикс двойного слэша

### ISSUE THREAD

**Issue by gadev** [dmi3yy/modx.evo.custom#476]
по текущему состоянию модх игнорирует двойной/тройной... слэш в урлах. т.е. при обращении к site.com///page показывается страница site.com/page. это нехорошо с точки зрения сео, поэтому хорошо бы добавить в ядро проверку.  для сохранения гибкости можно добавить в настройки выбор возможного действия: "склейка-редирект(по-умолчанию) / 404 / ничего не делать (если вдруг по какой-то причине нужно оставить текущее положение дел)".  
```
if (stristr($_SERVER['REQUEST_URI'], '//'))  {
//404
//$modx->sendErrorPage();

//редирект site.com//page -> site.com/page
$g = preg_replace("|[//\s]+|is", "/", $_SERVER['REQUEST_URI']);
$modx->sendRedirect($g);
}
```

**Comment by dmi3yy** [comment]
Это проще править на уровне htaccess
