### ISSUE TITLE
Не сохраняются параметры плагинов при обновлении

### ISSUE THREAD

**Issue by Pathologic** [dmi3yy/modx.evo.custom#501]
Можно проверить на SimpleGallery.

**Comment by Pathologic** [comment]
http://modx.im/blog/dmi3yy/5265.html#comment45463 - такое тоже происходит, видимо неверно объединяются массивы.

**Comment by dmi3yy** [comment]
Пофиксил сохранение параметров в 1.3.0 были косяки
