### ISSUE TITLE
Refused to set unsafe header "Connection"

### ISSUE THREAD

**Issue by dmitry53** [dmi3yy/modx.evo.custom#528]
Ошибка появляется в админке, версии пробывал разные, 1.0.9, 1.0.12, 1.2.1
Устанавливал на другой хостинг, ошибка повторяется.

**Comment by dmitry53** [comment]
Refused to set unsafe header "Connection"
send	@	mootools.js:2
request	@	mootools.js:2
updateMail	@	index.php?a=1&f=menu:26
(anonymous)	@	index.php?a=2:41

**Comment by dmi3yy** [comment]
Поставьте новую тему по умолчанию. MODxRE2_DropDown 
там ошибки нет уже

**Comment by dmi3yy** [comment]
https://github.com/dmi3yy/modx.evo.custom/archive/master.zip 
и вот эту версии 1.2.1-d9.1.7
