### ISSUE TITLE
Модернизирование "Очистить кеш"

### ISSUE THREAD

**Issue by sazanof** [dmi3yy/modx.evo.custom#534]
Вот идея: раздражает порой, что находясь на каком-то из ресурсов, или чанке, или модуле (неважно где) нужно бывает очистить кеш.
Но после очистки хотелось бы увидеть либо модальное окно, либо просто алярм что кеш успешно очищен. Чтобы он обновлялся в фоне и не сбрасывал менеджера со страницы, на которой он находится.
Кеш обновился в фоне, модальное окно всплыло, менеджер его закрыл,остался на редактировании сниппета, документа,или еще чего....))
![2017-06-22_14-34-37](https://user-images.githubusercontent.com/3595562/27432296-487806a0-5758-11e7-99b3-299b700764c3.jpg)

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/21
