### ISSUE TITLE
Не активный чекбокс

### ISSUE THREAD

**Issue by F1fanatik** [dmi3yy/modx.evo.custom#536]
(http://images.vfl.ru/ii/1498297211/1227d57c/17692831.jpg) невозможно активизировать чекбокс, галка не ставится.. пробовал в Хроме, Опера. В ИЕ11, ФФ, Мозиле работает

**Comment by dmi3yy** [comment]
Неактуальная кнопка она все равно не пашет и не работала никогда :) 
как минимум. с версии 1.0.2 ) 
удалили
