### ISSUE TITLE
Глюк со скрытием полей в mm_rules 

### ISSUE THREAD

**Issue by Typodin** [dmi3yy/modx.evo.custom#539]
Вот такой код в mm_rules в сборке 1.2.1-d9.1.7
`mm_hideFields("parent", "", "5");`
скрывает поле content

**Comment by 64j** [comment]
плагин MM привязан к вёрстке, и малейшие изменения на нём сказываются.
https://api.monosnap.com/rpc/file/download?id=M5BV7GLCbfC8PJBb7265IiYnsJut5v

**Comment by dmi3yy** [comment]
иправленно  в 1.2.2 

Новые баги просьба писать тут: 
https://github.com/evolution-cms/evolution/issues
