### ISSUE TITLE
modx->getConfig

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#570]
На этом месте очень долго думает во всех версиях после официальной. Обновляться не имеет смысла.

Файл assets/cache/siteCache.idx.php весит 32мб

Да, ресурсов много, ну и что.

**Comment by atomoc** [comment]
Обработка php главной на официальной версии 0.3, на всех после неё 4.

**Comment by dmi3yy** [comment]
Если очень много ресурсов то поставить  http://take.ms/ISF79l и будет все ок. 
Офф версия и моя сборка отличается только базовыми настройками все остальное в том числе парсер и кеш 1 в 1 :) 

Сейчас проверю еще пару вещей и будет свежи релиз в котором исправил пару критических косяков

**Comment by atomoc** [comment]
Я тоже так думал, вчера, но не получилось, пошёл спать, проснулся и понял где проблема, написал issue.

**Comment by atomoc** [comment]
Главная страница modx тоже открывается долго: 3-4 с.

**Comment by atomoc** [comment]
Отключал все плагины, тоже самое.

**Comment by atomoc** [comment]
php_value memory_limit 1000M
без этого вообще сайт и система отказывались работать

**Comment by atomoc** [comment]
> Если очень много ресурсов то поставить http://take.ms/ISF79l и будет все ок

Возможно этот параметр просто не работает

**Comment by atomoc** [comment]
Установил последнюю версию и проверил, везде где есть условие с aliaslistingfolder добавил 1|| - долго, и 0&& - точно так же долго.

**Comment by dmi3yy** [comment]
Стукни в личку пообщаемся

**Comment by atomoc** [comment]
Выяснилось в чём дело. 

Если в документах убран параметр "Участвует в URL" то все его дочерние документы попадают в кеш. Как только я запустил команду:
```
UPDATE `modx_site_content` SET `alias_visible`=1 WHERE 1
```
проблема решилась. Низжайший поклон, Дмитрий.
