### ISSUE TITLE
Фильтры не работают в $modx->getChunk

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#571]
Ни PHx, ни новые фильтры не работают, если чанк подгружается в сниппете, чего не было в 1.2.1 версии, там PHx это делал.

**Comment by atomoc** [comment]
Хотя нет, PHx до сих пор работает, но не работает в другом случае.

**Comment by atomoc** [comment]
Ага, не работает если прям в шаблоне их использовать. Вообще странно...

**Comment by atomoc** [comment]
То есть с выключенным phx, но включенном фильтре работает в шаблонах, и наоборот, если включен phx не работает в шаблонах, но работает в сниппетах, в $modx->getChunk. Такое разное поведение уже указывает на ошибку.

**Comment by dmi3yy** [comment]
Я вообще не люблю phx и фильтры поэтому не тестил что куда и в целом не особо собираюсь :)

**Comment by atomoc** [comment]
Это хорошо, я тоже их не люблю, но почему они работали, а потом вдруг
перестали ты же можешь знать)

11 июля 2017 г. 23:24 пользователь "Dmytro Lukianenko" <
notifications@github.com> написал:

**Comment by atomoc** [comment]
Ясно, значит ты знал об этом последствии, когда принимал решение. Жестоковато конечно
