### ISSUE TITLE
KCFinder не грузится при большом числе подпапок assets/images

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#573]
Надо бы отключить их преиндексацию.

**Comment by atomoc** [comment]
Всего лишь 20 папок. А вот внутри некоторых из них тысячи и тысячи, их лучше не открывать даже на компе.
![2017-07-13 13-54-22](https://user-images.githubusercontent.com/465108/28163204-ce48561a-67d2-11e7-80b3-5bc8f7f2b563.png)

**Comment by atomoc** [comment]
Как быть с правкой файлов этого менеджера? Какие этапы следует учесть?

**Comment by dmi3yy** [comment]
Да можно заменить вообще на новый но надо учесть транслитерацию при загрузке это важно + параметры из последней вкладки в настройках MODX 
тогда можно будет заменить

**Comment by atomoc** [comment]
Мне даже помог бы вариант с добавлением поля в конфигурацию modx, для изменения папки выбора картинок в этом менеджере, так как я изменил политику выбора картинок в этом проекте. Я бы с удовольствием поделился своим решением, но в нём много зависимостей, которые не дают мне так легко этого добиться.

**Comment by atomoc** [comment]
![2017-07-13 13-59-27](https://user-images.githubusercontent.com/465108/28163370-82ee7644-67d3-11e7-961d-6a6a12a0c377.png)

**Comment by atomoc** [comment]
> можно заменить вообще на новый
Это конечно отличный вариант, но, скорей всего, понадобится написать его самим.

**Comment by atomoc** [comment]
> Мне даже помог бы вариант с добавлением поля в конфигурацию modx

Плагином реально решить мою проблему?

**Comment by dmi3yy** [comment]
Только менять файловый редактор пока руки до текущего не дойдут
