### ISSUE TITLE
При обновлении или при смене темы не сохраняются новые ресурсы

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#574]
Сейчас, в последней версии (1.2.2-d10), если сменить тему, то при попытке создать ресурс выводится следующее:
![2017-07-13 20-42-19](https://user-images.githubusercontent.com/465108/28179868-002ef7c2-680c-11e7-9559-66702c4c6206.png)

**Comment by atomoc** [comment]
Имеется в виду с dropdown и обратно.

**Comment by atomoc** [comment]
Вижу сейчас что не только в последней, это ещё и в официальной имеется.

**Comment by atomoc** [comment]
Стоп, это моих рук дело. Эту переменную я, вроде как, использовал, чтобы проверять, авторизован ли пользователь или не выключен ли сервер, при сохранении ресурса, чтобы не терять случайно все вбитые в поля данные.

**Comment by dmi3yy** [comment]
Там нет jquery 1.9 в ядре ищите в плагинах что то

Отправлено с iPhone

**Comment by atomoc** [comment]
Я не понимаю, почему в плагине на событии OnDocFormRender в коде через $.post стало невозможно получить элементы $_SESSION. Жесть какая-то

**Comment by dmi3yy** [comment]
В смысле через пост получить сессию?

**Comment by atomoc** [comment]
Да, ведь нужно иметь возможность при сохранении проверить, авторизован ли ещё редактор

**Comment by atomoc** [comment]
А там пусто, какой метод не взять:
![2017-07-13 22-19-25](https://user-images.githubusercontent.com/465108/28183789-6af976c4-6819-11e7-9976-b841691d5857.png)

**Comment by atomoc** [comment]
Откатываюсь на предыдущую версию (1.2.1) тоже самое, как буд то так и было...

**Comment by atomoc** [comment]
Решил удалением cookie.
