### ISSUE TITLE
Стиль Dropdown значительно уступает по скорости обычным

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#577]
Редакторы жалуются, что тормоза жуткие. Видимо это связано с большим числом элементов страницы. Пока что до меня дошёл следующий список:
1. Курсор подтормаживает при ведении им по дереву ресурсов (видимо речь идёт о выделении при перемещении - солидарен);

Мои личные замечания:
2. Прокрутка в основном фрейме подтормаживает;
3. Тормоза в верхнем меню очень заметные. Видимо это тоже связано с большим числом элементов на странице.

Пока такой список, надеюсь он не разрастётся.

**Comment by atomoc** [comment]
Выяснил с чем связаны все эти пункты! Проблема в большом числе открытых в дереве ресурсов, на их обработку браузер тратит много ресурсов (надо понять почему). Как только ветку с тремя тысячами ресурсов скрываешь, проблема исчезает.

**Comment by dmi3yy** [comment]
Кинь доступ в личку подозреваю большое колво js елементов + не совсем новый комп вот браузер и вешается

Отправлено с iPhone

**Comment by dmi3yy** [comment]
Так надо скрывать из дерева такое кол во ресурсов ;)

Отправлено с iPhone

**Comment by dmi3yy** [comment]
Проверил работает все шутстро 
и пишем вот сюда: 
https://github.com/evolution-cms/evolution/issues
