### ISSUE TITLE
Необходимо установить лимит на обработку запроса для открытия ветки в дереве ресурсов

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#578]
Так как есть ветки с неимоверным числом ресурсов (100000) и они никогда не откроются и ждать их открытия не за чем. Хотя, возможно, лучше при нажатии на плюс считать количество и, если их больше 10000, выводить сообщение о том, что происходит попытка открыть слишком большой список подресурсов и что следует воспользоваться обзором ресурса.

**Comment by atomoc** [comment]
Хотя можно больше уделить внимания развитию терпения и умению отдыхать (когда случайно нажал на этот плюс), в конце концов чай выпить или протереть пыль не помешает в любом случае :)

**Comment by dmi3yy** [comment]
Скрывать из дерева такие ветки самое верное решение 

Отправлено с iPhone

**Comment by atomoc** [comment]
А как это делать?

**Comment by dmi3yy** [comment]
Кнопка не показывать дочерние документы;)

Отправлено с iPhone

**Comment by atomoc** [comment]
То есть такого решения ещё нет?
