### ISSUE TITLE
Всплывашки перекрываются полями перенесёнными managermanager

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#579]
![2017-07-14 00-32-02](https://user-images.githubusercontent.com/465108/28188811-239ac392-682c-11e7-835a-915142bb3479.png)
Не знаю, возможно есть другие решения по управлению полями, я не нашёл, так что с managermanager надо научиться дружить :)

**Comment by 64j** [comment]
попробуйте такое решение https://github.com/64j/templatesEdit2

<img src="http://wexar.ru/uploads/images/v-razrabotke/2015-11-1015.04.37.png" />

<img src="http://wexar.ru/uploads/images/v-razrabotke/2015-11-1014.56.57.png" />

**Comment by 64j** [comment]
проверил на EVO 1.3, всё работает

<img src="https://api.monosnap.com/rpc/file/download?id=RvL6gFahJsMe9BvujWdfUwraBBcX8w" />

**Comment by atomoc** [comment]
Спасибо!
