### ISSUE TITLE
В модуле managermanager невидно списка добавляемых правил

### ISSUE THREAD

**Issue by atomoc** [dmi3yy/modx.evo.custom#580]
![2017-07-14 00-35-22](https://user-images.githubusercontent.com/465108/28188908-70e8c54a-682c-11e7-81a5-f023bd9ecb92.png)

**Comment by atomoc** [comment]
Убирается проблема таким вот методом, но я не уверен что это не обернётся другой.
![2017-07-14 00-38-49](https://user-images.githubusercontent.com/465108/28189042-fe2aaae0-682c-11e7-988f-6e9cb25c62d2.png)

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/25
