### ISSUE TITLE
Ditto не рендерит TV если их значение по умолчанию

### ISSUE THREAD

**Issue by radist** [dmi3yy/modx.evo.custom#80]
Например если в значение tv по умолчанию записать @EVAL зависящий от идентификатора документа, то результат  вычислится не верно, так как getTVDisplayFormat не требует обязательно идентификатор документа и в случае его отсутствия подставит текущий документ, что в случае с ditto не верно. 

Проблемный участок в примерно с 796 строки https://github.com/dmi3yy/modx.evo.custom/blob/master/assets/snippets/ditto/classes/ditto.class.inc.php#L796 

Место ошибочное:

http://paste.org.ru/?h3gzi9 

Исправленный вариант:

http://paste.org.ru/?g80brs

Вызовы getTVDisplayFormat перенесены ниже, на момент когда известен идентификатор документа. Кроме того во втором вызове getTVDisplayFormat исправлено имя переменной содержащей идентификатор документа.

**Comment by dmi3yy** [comment]
Не совсем понял в вариате решения, не могли бы просто прислать пулреквест. 
Это было бы удобней и быстрее
