### ISSUE TITLE
При выставлении приоритетов плагинов, хочется видеть отключенные

### ISSUE THREAD

**Issue by dmi3yy** [dmi3yy/modx.evo.custom#85]
------------------------
При выставлении приоритетов плагинов, хочется видеть отключенные, чтобы при включении они сразу занимали своё место
manager\actions\mutate_plugin_priority.dynamic.php
в 45 строке (в SQL) добавить поле ", plugs.disabled"
и
$evtLists .= '<li id="item_'.$plugins['pluginid'].'">'.$plugins['name'].'</li>';
заменить на
$evtLists .= '<li id="item_'.$plugins['pluginid'].'"'.($plugins['disabled']?' style="color:#AAA"':'').'>'.$plugins['name'].($plugins['disabled']?' (hide)':'').'</li>';

**Comment by AgelxNash** [comment]
Вопрос уже разрешен.
